<a href="https://colab.research.google.com/github/Diana102001/Ranking-medical-files-pipeline/blob/main/Data_preparation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
with open('/content/drive/MyDrive/NLP/train.txt', 'r') as file:
    data = file.read()
    print(data)

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)

In [ ]:
from nltk.probability import FreqDist
from nltk.tokenize import word_tokenize

In [ ]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [ ]:
import nltk
from nltk.probability import FreqDist
tokens = nltk.word_tokenize(data)
dist = FreqDist(tokens)
print(dist)

<FreqDist with 32267 samples and 533457 outcomes>

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_excel('/content/drive/MyDrive/NLP/train.xlsx')
df

            ID                                           Document
0       MED-10  statin breast cancer survival nationwide cohor...
1       MED-14  statin diagnosis breast cancer survival popula...
2      MED-118  alkylphenols human milk relations dietary habi...
3      MED-301  methylmercury potential environmental risk fac...
4      MED-306  sensitivity continuous performance test cpt ag...
...        ...                                                ...
3607  MED-5367  relationship plasma carotenoids depressive sym...
3608  MED-5368  suicide mortality relation dietary intake num ...
3609  MED-5369  suicide mortality european union pubmed ncbi a...
3610  MED-5370  long chain omega num fatty acids intake fish c...
3611  MED-5371  omega num fatty acids treatment depression sys...

[3612 rows x 2 columns]

In [ ]:
undersampled_df = df.sample(n=500, random_state=42)  # Set random_state for reproducibility
undersampled_df.head()

            ID                                           Document
839   MED-1768  milk responsible male reproductive disorders p...
2630  MED-4257  systematic review body fat distribution mortal...
32     MED-724  flatulence--causes relation diet remedies pubm...
2398  MED-3944  pain reduction improvement range motion daily ...
411   MED-1273  amyotrophic lateral sclerosis case-control stu...

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
nltk.download('wordnet')

NameError: name 'nltk' is not defined

In [ ]:
from textblob import TextBlob, Word

df['2nd_column_lemmatized'] = df['Document'].apply(lambda x: ' '.join([Word(word).lemmatize() for word in x.split()]))
df.head()

,ID,Document,2nd_column_lemmatized
0,MED-10,statin breast cancer survival nationwide cohor...,statin breast cancer survival nationwide cohor...
1,MED-14,statin diagnosis breast cancer survival popula...,statin diagnosis breast cancer survival popula...
2,MED-118,alkylphenols human milk relations dietary habi...,alkylphenols human milk relation dietary habit...
3,MED-301,methylmercury potential environmental risk fac...,methylmercury potential environmental risk fac...
4,MED-306,sensitivity continuous performance test cpt ag...,sensitivity continuous performance test cpt ag...

In [ ]:
from nltk.stem import SnowballStemmer
stemmer = SnowballStemmer("english")

# Apply the Snowball stemmer to the 2nd column of the dataset
df['2nd_column_stemmed'] = df['Document'].apply(lambda x: ' '.join([stemmer.stem(word) for word in x.split()]))

# Print the updated dataset
df.head()

,ID,Document,2nd_column_lemmatized,2nd_column_stemmed
0,MED-10,statin breast cancer survival nationwide cohor...,statin breast cancer survival nationwide cohor...,statin breast cancer surviv nationwid cohort s...
1,MED-14,statin diagnosis breast cancer survival popula...,statin diagnosis breast cancer survival popula...,statin diagnosi breast cancer surviv populatio...
2,MED-118,alkylphenols human milk relations dietary habi...,alkylphenols human milk relation dietary habit...,alkylphenol human milk relat dietari habit cen...
3,MED-301,methylmercury potential environmental risk fac...,methylmercury potential environmental risk fac...,methylmercuri potenti environment risk factor ...
4,MED-306,sensitivity continuous performance test cpt ag...,sensitivity continuous performance test cpt ag...,sensit continu perform test cpt age num year d...

In [ ]:
from collections import Counter

# Split the 'snowball' column into individual words
words = df['2nd_column_stemmed'].str.split(expand=True).stack()

# Count the frequency of each word
word_counts = Counter(words)

# Get the top 25 most common words
top_25_words = word_counts.most_common(200)

print(top_25_words)

[('num', 45538), ('studi', 5347), ('risk', 3931), ('effect', 3659), ('abstract', 3634), ('cancer', 3307), ('intak', 3133), ('diet', 3060), ('increas', 2983), ('pubm', 2811), ('ncbi', 2758), ('signific', 2731), ('result', 2629), ('diseas', 2489), ('patient', 2463), ('food', 2441), ('dietari', 2378), ('level', 2141), ('consumpt', 2057), ('group', 2027), ('cell', 1806), ('control', 1765), ('human', 1753), ('activ', 1726), ('age', 1716), ('ci', 1679), ('women', 1679), ('year', 1629), ('health', 1624), ('compar', 1591), ('factor', 1572), ('concentr', 1550), ('total', 1494), ('associ', 1493), ('acid', 1472), ('high', 1379), ('includ', 1371), ('conclus', 1370), ('reduc', 1307), ('treatment', 1260), ('method', 1257), ('subject', 1257), ('relat', 1237), ('data', 1214), ('exposur', 1183), ('measur', 1174), ('product', 1172), ('lower', 1160), ('suggest', 1152), ('trial', 1125), ('protein', 1122), ('diabet', 1088), ('breast', 1082), ('higher', 1070), ('assess', 1048), ('decreas', 1044), ('men', 1041), ('clinic', 1038), ('report', 1038), ('blood', 1021), ('review', 1006), ('meat', 996), ('sampl', 990), ('show', 978), ('evid', 972), ('observ', 945), ('potenti', 942), ('function', 941), ('develop', 913), ('fat', 909), ('weight', 898), ('consum', 897), ('prevent', 893), ('determin', 878), ('serum', 878), ('examin', 875), ('particip', 872), ('found', 870), ('type', 869), ('investig', 868), ('differ', 863), ('case', 861), ('object', 857), ('test', 852), ('healthi', 841), ('improv', 829), ('antioxid', 826), ('mortal', 823), ('time', 817), ('veget', 816), ('cardiovascular', 815), ('cholesterol', 813), ('respons', 812), ('evalu', 807), ('plasma', 797), ('fruit', 795), ('popul', 791), ('present', 784), ('bodi', 781), ('supplement', 781), ('vitamin', 775), ('incid', 753), ('day', 752), ('addit', 749), ('estim', 741), ('random', 740), ('rate', 739), ('children', 734), ('analysi', 732), ('low', 726), ('intervent', 721), ('background', 716), ('week', 715), ('fish', 712), ('obes', 706), ('adult', 676), ('model', 673), ('ratio', 670), ('symptom', 667), ('individu', 665), ('preval', 662), ('find', 657), ('vegetarian', 652), ('extract', 646), ('mechan', 644), ('anim', 643), ('insulin', 642), ('reduct', 635), ('import', 631), ('metabol', 630), ('role', 629), ('identifi', 621), ('death', 620), ('research', 618), ('process', 617), ('cohort', 612), ('nutrit', 609), ('placebo', 603), ('lipid', 599), ('baselin', 593), ('milk', 584), ('design', 581), ('major', 571), ('common', 563), ('oxid', 555), ('recent', 550), ('daili', 547), ('posit', 546), ('sourc', 544), ('content', 542), ('number', 542), ('adjust', 539), ('glucos', 538), ('period', 537), ('fatti', 534), ('perform', 531), ('score', 528), ('prospect', 526), ('oil', 524), ('compound', 524), ('similar', 522), ('tea', 521), ('provid', 520), ('state', 516), ('rang', 512), ('inhibit', 509), ('induc', 508), ('lifestyl', 506), ('protect', 503), ('month', 501), ('chronic', 496), ('outcom', 496), ('medic', 491), ('aim', 486), ('system', 485), ('infect', 483), ('chang', 483), ('index', 482), ('base', 474), ('drug', 471), ('benefit', 470), ('recommend', 468), ('detect', 465), ('correl', 464), ('tissu', 461), ('energi', 454), ('specif', 450), ('dose', 449), ('copyright', 447), ('meal', 445), ('interv', 443), ('affect', 440), ('organ', 433), ('prostat', 433), ('growth', 431), ('plant', 426), ('pattern', 424), ('smoke', 424), ('combin', 423), ('contribut', 422)]

In [ ]:
from pickle import dumps
lexicon = [w for w,f in top_25_words if (f > 2000) ]
dumps = ['the','a','year', 'month', 'week', 'day', 'hour', 'minute', 'second', 'sunday', 'monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday','due','because','age']
lexicon=lexicon+dumps
lexicon

['num',
 'studi',
 'risk',
 'effect',
 'abstract',
 'cancer',
 'intak',
 'diet',
 'increas',
 'pubm',
 'ncbi',
 'signific',
 'result',
 'diseas',
 'patient',
 'food',
 'dietari',
 'level',
 'consumpt',
 'group',
 'the',
 'a',
 'year',
 'month',
 'week',
 'day',
 'hour',
 'minute',
 'second',
 'sunday',
 'monday',
 'tuesday',
 'wednesday',
 'thursday',
 'friday',
 'saturday',
 'due',
 'because',
 'age']

In [ ]:
for word in lexicon:
    df['2nd_column_stemmed_after_deletion'] = df['2nd_column_stemmed'].str.replace(word, '')

In [ ]:
df.head()

,ID,Document,2nd_column_lemmatized,2nd_column_stemmed,2nd_column_stemmed_after_deletion
0,MED-10,statin breast cancer survival nationwide cohor...,statin breast cancer survival nationwide cohor...,statin breast cancer surviv nationwid cohort s...,statin breast cancer surviv nationwid cohort s...
1,MED-14,statin diagnosis breast cancer survival popula...,statin diagnosis breast cancer survival popula...,statin diagnosi breast cancer surviv populatio...,statin diagnosi breast cancer surviv populatio...
2,MED-118,alkylphenols human milk relations dietary habi...,alkylphenols human milk relation dietary habit...,alkylphenol human milk relat dietari habit cen...,alkylphenol human milk relat dietari habit cen...
3,MED-301,methylmercury potential environmental risk fac...,methylmercury potential environmental risk fac...,methylmercuri potenti environment risk factor ...,methylmercuri potenti environment risk factor ...
4,MED-306,sensitivity continuous performance test cpt ag...,sensitivity continuous performance test cpt ag...,sensit continu perform test cpt age num year d...,sensit continu perform test cpt num year deve...

In [ ]:
word_counts = Counter(words)

In [ ]:
print(word_counts)

Counter({'num': 45538, 'studi': 5347, 'risk': 3931, 'effect': 3659, 'abstract': 3634, 'cancer': 3307, 'intak': 3133, 'diet': 3060, 'increas': 2983, 'pubm': 2811, 'ncbi': 2758, 'signific': 2731, 'result': 2629, 'diseas': 2489, 'patient': 2463, 'food': 2441, 'dietari': 2378, 'level': 2141, 'consumpt': 2057, 'group': 2027, 'cell': 1806, 'control': 1765, 'human': 1753, 'activ': 1726, 'age': 1716, 'ci': 1679, 'women': 1679, 'year': 1629, 'health': 1624, 'compar': 1591, 'factor': 1572, 'concentr': 1550, 'total': 1494, 'associ': 1493, 'acid': 1472, 'high': 1379, 'includ': 1371, 'conclus': 1370, 'reduc': 1307, 'treatment': 1260, 'method': 1257, 'subject': 1257, 'relat': 1237, 'data': 1214, 'exposur': 1183, 'measur': 1174, 'product': 1172, 'lower': 1160, 'suggest': 1152, 'trial': 1125, 'protein': 1122, 'diabet': 1088, 'breast': 1082, 'higher': 1070, 'assess': 1048, 'decreas': 1044, 'men': 1041, 'clinic': 1038, 'report': 1038, 'blood': 1021, 'review': 1006, 'meat': 996, 'sampl': 990, 'show': 978, 'evid': 972, 'observ': 945, 'potenti': 942, 'function': 941, 'develop': 913, 'fat': 909, 'weight': 898, 'consum': 897, 'prevent': 893, 'determin': 878, 'serum': 878, 'examin': 875, 'particip': 872, 'found': 870, 'type': 869, 'investig': 868, 'differ': 863, 'case': 861, 'object': 857, 'test': 852, 'healthi': 841, 'improv': 829, 'antioxid': 826, 'mortal': 823, 'time': 817, 'veget': 816, 'cardiovascular': 815, 'cholesterol': 813, 'respons': 812, 'evalu': 807, 'plasma': 797, 'fruit': 795, 'popul': 791, 'present': 784, 'bodi': 781, 'supplement': 781, 'vitamin': 775, 'incid': 753, 'day': 752, 'addit': 749, 'estim': 741, 'random': 740, 'rate': 739, 'children': 734, 'analysi': 732, 'low': 726, 'intervent': 721, 'background': 716, 'week': 715, 'fish': 712, 'obes': 706, 'adult': 676, 'model': 673, 'ratio': 670, 'symptom': 667, 'individu': 665, 'preval': 662, 'find': 657, 'vegetarian': 652, 'extract': 646, 'mechan': 644, 'anim': 643, 'insulin': 642, 'reduct': 635, 'import': 631, 'metabol': 630, 'role': 629, 'identifi': 621, 'death': 620, 'research': 618, 'process': 617, 'cohort': 612, 'nutrit': 609, 'placebo': 603, 'lipid': 599, 'baselin': 593, 'milk': 584, 'design': 581, 'major': 571, 'common': 563, 'oxid': 555, 'recent': 550, 'daili': 547, 'posit': 546, 'sourc': 544, 'content': 542, 'number': 542, 'adjust': 539, 'glucos': 538, 'period': 537, 'fatti': 534, 'perform': 531, 'score': 528, 'prospect': 526, 'oil': 524, 'compound': 524, 'similar': 522, 'tea': 521, 'provid': 520, 'state': 516, 'rang': 512, 'inhibit': 509, 'induc': 508, 'lifestyl': 506, 'protect': 503, 'month': 501, 'chronic': 496, 'outcom': 496, 'medic': 491, 'aim': 486, 'system': 485, 'infect': 483, 'chang': 483, 'index': 482, 'base': 474, 'drug': 471, 'benefit': 470, 'recommend': 468, 'detect': 465, 'correl': 464, 'tissu': 461, 'energi': 454, 'specif': 450, 'dose': 449, 'copyright': 447, 'meal': 445, 'interv': 443, 'affect': 440, 'organ': 433, 'prostat': 433, 'growth': 431, 'plant': 426, 'pattern': 424, 'smoke': 424, 'combin': 423, 'contribut': 422, 'normal': 422, 'exercis': 421, 'greater': 420, 'unit': 415, 'general': 412, 'highest': 412, 'epidemiolog': 409, 'condit': 409, 'demonstr': 407, 'ad': 407, 'stress': 407, 'conduct': 406, 'pressur': 406, 'mg': 402, 'resist': 402, 'support': 401, 'express': 401, 'curcumin': 399, 'trend': 395, 'sensit': 392, 'confid': 390, 'physic': 390, 'follow-up': 389, 'qualiti': 387, 'larg': 385, 'relationship': 383, 'questionnair': 383, 'fiber': 383, 'cognit': 381, 'ingest': 381, 'analys': 380, 'influenc': 380, 'limit': 380, 'mass': 377, 'produc': 376, 'select': 375, 'depress': 375, 'natur': 374, 'previous': 373, 'frequenc': 373, 'lead': 372, 'inform': 371, 'status': 371, 'fast': 370, 'juic': 367, 'disord': 366, 'water': 366, 'colon': 365, 'event': 364, 'amount': 360, 'heart': 360, 'due': 359, 'involv': 359, 'statist': 358, 'elsevi': 358, 'therapi': 357, 'shown': 354, 'remain': 353, 'regress': 353, 'reserv': 353, 'syndrom': 352, 'brain': 349, 'life': 346, 'right': 344, 'public': 342, 'publish': 342, 'collect': 342, 'liver': 342, 'arteri': 340, 'coronari': 339, 'nation': 338, 'current': 338, 'toxic': 337, 'occur': 336, 'consist': 336, 'oral': 334, 'loss': 330, 'primari': 328, 'vegan': 328, 'nut': 323, 'nutrient': 321, 'sever': 321, 'meta-analysi': 321, 'male': 319, 'hr': 317, 'hormon': 317, 'agent': 313, 'inflammatori': 313, 'survey': 311, 'compon': 311, 'multipl': 309, 'receiv': 309, 'advers': 307, 'damag': 306, 'tumor': 305, 'impact': 305, 'drink': 305, 'complet': 303, 'analyz': 303, 'alcohol': 302, 'urinari': 302, 'treat': 301, 'countri': 300, 'red': 300, 'endotheli': 298, 'assay': 298, 'coffe': 295, 'form': 293, 'progress': 293, 'valu': 291, 'practic': 290, 'gene': 290, 'environment': 289, 'elev': 289, 'vitro': 289, 'acut': 288, 'averag': 288, 'cd': 288, 'consid': 286, 'set': 285, 'contamin': 284, 'immun': 284, 'invers': 283, 'obtain': 280, 'direct': 280, 'hazard': 279, 'earli': 278, 'promot': 277, 'pathway': 277, 'isol': 277, 'cook': 276, 'cvd': 276, 'urin': 276, 'histori': 274, 'properti': 274, 'lipoprotein': 274, 'systemat': 273, 'efficaci': 271, 'main': 271, 'sex': 271, 'dna': 271, 'rr': 271, 'composit': 270, 'presenc': 270, 'benefici': 269, 'literatur': 269, 'link': 267, 'receptor': 267, 'skin': 266, 'part': 266, 'lowest': 265, 'confirm': 265, 'hospit': 264, 'discuss': 262, 'area': 261, 'intestin': 260, 'biolog': 260, 'signal': 259, 'pesticid': 259, 'search': 258, 'peopl': 258, 'initi': 257, 'calcul': 255, 'muscl': 255, 'bowel': 254, 'target': 253, 'requir': 253, 'inflamm': 253, 'profil': 252, 'bmi': 250, 'proport': 249, 'regul': 249, 'soy': 249, 's': 248, 'free': 247, 'stroke': 247, 'chemic': 246, 'odd': 245, 'small': 244, 'indic': 243, 'enhanc': 243, 'standard': 243, 'restrict': 243, 'purpos': 242, 'independ': 241, 'manag': 241, 'egg': 240, 'green': 240, 'femal': 239, 'variabl': 238, 'pain': 238, 'older': 238, 'american': 237, 'moder': 236, 'chicken': 235, 'marker': 235, 'capac': 234, 'eat': 234, 'caffein': 234, 'point': 232, 'behavior': 231, 'safeti': 230, 'calcium': 227, 'diagnosi': 226, 'impair': 226, 'wide': 226, 'experiment': 225, 'alter': 225, 'polyphenol': 225, 'establish': 224, 'interact': 224, 'hypertens': 224, 'articl': 224, 'strong': 223, 'estrogen': 223, 'apoptosi': 222, 'care': 222, 'surviv': 220, 'dri': 220, 'e': 219, 'medicin': 219, 'long-term': 219, 'need': 219, 'strategi': 218, 'action': 217, 'volunt': 217, 'person': 217, 'declin': 217, 'white': 217, 'dysfunct': 216, 'western': 216, 'versus': 216, 'negat': 215, 'approach': 214, 'speci': 214, 'phenol': 214, 'satur': 212, 'appear': 210, 'mediterranean': 209, 'cultur': 208, 'caus': 208, 'region': 208, 'ldl': 207, 'repres': 207, 'infant': 206, 'ed': 206, 'frequent': 205, 'implic': 205, 'black': 205, 'dairi': 205, 'depend': 204, 'tradit': 204, 'grain': 203, 'defin': 203, 'excret': 202, 'rich': 202, 'hour': 202, 'mm': 202, 'iron': 202, 'il': 201, 'understand': 201, 'antibodi': 201, 'cox': 199, 'adher': 199, 'postprandi': 199, 'beverag': 199, 'comparison': 199, 'sugar': 199, 'asthma': 199, 'line': 198, 'convent': 195, 'approxim': 195, 'case-control': 194, 'futur': 194, 'criteria': 194, 'accumul': 194, 'postmenopaus': 194, 'databas': 193, 'vascular': 193, 'vivo': 193, 'diagnos': 192, 'gastrointestin': 192, 'relev': 192, 'reveal': 192, 'lung': 192, 'continu': 191, 'hypothesi': 191, 'poultri': 191, 'characterist': 190, 'serv': 190, 'pregnanc': 190, 'prepar': 189, 'genet': 188, 'phase': 187, 'cellular': 185, 'carbohydr': 185, 'u': 185, 'mercuri': 185, 'al': 185, 'expos': 184, 'global': 184, 'enzym': 184, 'molecular': 184, 'confound': 183, 'program': 183, 'strain': 183, 'therapeut': 182, 'modul': 182, 'triglycerid': 182, 'work': 182, 'author': 182, 'omnivor': 182, 'deriv': 182, 'multivari': 181, 'min': 181, 'median': 180, 'excess': 180, 'focus': 179, 'origin': 179, 'interest': 179, 'lignan': 179, 'and/or': 178, 'absorpt': 178, 'sodium': 177, 'fresh': 177, 'attribut': 176, 'complex': 176, 'site': 176, 'concern': 176, 'regular': 176, 'educ': 175, 'refer': 175, 'explain': 175, 'metabolit': 175, 'format': 174, 'varieti': 173, 'world': 172, 'physician': 172, 'cost': 172, 'pig': 172, 'singl': 172, 'phytochem': 172, 'play': 171, 'advanc': 171, 'bone': 171, 'defici': 171, 'dementia': 171, 'pathogen': 171, 'biomark': 170, 'prolifer': 170, 'young': 170, 'durat': 169, 'physiolog': 169, 'pool': 169, 'predict': 169, 'exist': 168, 'subsequ': 168, 'vari': 168, 'record': 167, 'paramet': 166, 'sd': 166, 'modifi': 166, 'habit': 165, 'reaction': 165, 'flavonoid': 165, 'problem': 165, 'stimul': 165, 'experi': 164, 'cross-sect': 164, 'oxygen': 163, 'rat': 163, 'carcinogen': 163, 'knowledg': 163, 'abil': 163, 'bioavail': 163, 'densiti': 163, 'industri': 162, 'low-fat': 162, 'childhood': 161, 'essenti': 160, 'intens': 160, 'intern': 160, 'overweight': 160, 'kg': 160, 'administr': 159, 'basi': 159, 'end': 159, 'double-blind': 158, 'inhibitor': 158, 'amino': 158, 'recurr': 157, 'feed': 157, 'platelet': 157, 'potato': 157, 'atherosclerosi': 156, 'famili': 156, 'mice': 156, 'valid': 156, 'toler': 155, 'degre': 154, 'cycl': 154, 'percentag': 153, 'constip': 153, 'term': 152, 'ill': 152, 'gain': 152, 'character': 151, 'salt': 151, 'anthocyanin': 150, 'account': 150, 'size': 150, 'mediat': 149, 'challeng': 149, 'telomer': 149, 'sleep': 149, 'screen': 149, 'mild': 148, 'lack': 148, 'summari': 148, 'persist': 148, 'de': 148, 'hepat': 148, 'suppress': 147, 'adipos': 147, 'circul': 147, 'substanti': 146, 'stage': 146, 'colorect': 146, 'load': 145, 'contrast': 145, 'kidney': 144, 'contain': 144, 'emerg': 144, 'date': 144, 'pancreat': 144, 'percent': 144, 'appl': 144, 'raw': 144, 'order': 143, 'propos': 143, 'fibr': 143, 'cocoa': 143, 'secret': 142, 'beef': 142, 'bacteria': 142, 'alzheim': 142, 'expect': 142, 'all-caus': 141, 'reactiv': 141, 'allergi': 141, 'anti-inflammatori': 140, 'sperm': 140, 'structur': 140, 'explor': 139, 'made': 139, 'mellitus': 139, 'consider': 139, 'guidelin': 139, 'coli': 139, 'generat': 139, 'assign': 139, 'broccoli': 139, 'matern': 139, 'central': 138, 'adolesc': 138, 'rice': 138, 'secondari': 137, 'burden': 137, 'possibl': 136, 'quintil': 136, 'separ': 135, 'farm': 135, 'bacteri': 135, 'respond': 135, 'residu': 135, 'ii': 134, 'bean': 134, 'placebo-control': 134, 'tract': 134, 'critic': 133, 'key': 133, 'g/d': 133, 'seed': 132, 'materi': 132, 'ml': 132, 'altern': 131, 'pork': 131, 'distribut': 131, 'decad': 131, 'environ': 131, 'commerci': 131, 'calori': 131, 'achiev': 131, 'hg': 131, 'flaxse': 131, 'exhibit': 130, 'million': 130, 'cow': 130, 'logist': 129, 'lesion': 129, 'rapid': 129, 'allerg': 129, 'phosphorus': 128, 'make': 128, 'differenti': 128, 'chocol': 128, 'cherri': 128, 'renal': 127, 'maintain': 127, 'abnorm': 127, 'past': 127, 'mg/dl': 127, 'g/day': 127, 'safe': 126, 'conclud': 126, 'societi': 126, 'fraction': 126, 'carri': 126, 'elder': 126, 'wk': 126, 'categori': 126, 'heterogen': 126, 'omega': 126, 'ph': 126, 'mtorc': 126, 'ip': 126, 'count': 125, 'sexual': 125, 'worldwid': 124, 'mix': 124, 'live': 124, 'european': 124, 'crossov': 123, 'paper': 123, 'radic': 123, 'train': 122, 'berri': 122, 'pcb': 122, 'final': 121, 'fold': 121, 'modif': 121, 'subgroup': 121, 'rais': 120, 'applic': 120, 'quartil': 120, 'light': 120, 'mark': 119, 'miner': 119, 'complic': 119, 'recruit': 119, 'chd': 119, 'gluten': 119, 'respiratori': 118, 'surfac': 118, 'quantit': 118, 'scientif': 118, 'synthesi': 118, 'poor': 117, 'fructos': 117, 'antibiot': 117, 'carotenoid': 117, 'g': 117, 'mutagen': 117, 'injuri': 116, 'i': 116, 'issu': 116, 'orang': 116, 'communiti': 115, 'bind': 115, 'radiat': 115, 'tomato': 115, 'substanc': 115, 'peripher': 114, 'long': 114, 'worker': 114, 'gut': 114, 'mmol/l': 114, 'cranberri': 114, 'scale': 113, 'bp': 113, 'etiolog': 112, 'extens': 112, 'abdomin': 112, 'stool': 112, 'item': 112, 'tobacco': 112, 'probiot': 112, 'turmer': 112, 'birth': 111, 'cereal': 111, 'reproduct': 111, 'consequ': 111, 'pathogenesi': 111, 'local': 111, 'laboratori': 111, 'favor': 111, 'uptak': 111, 'igf': 111, 'document': 110, 'fmd': 110, 'sweet': 110, 'quantifi': 110, 'pufa': 110, 'attent': 109, 'randomis': 109, 'cytokin': 109, 'linear': 109, 'balanc': 109, 'methyl': 109, 'melatonin': 109, 'legum': 108, 'summar': 108, 'mean': 108, 'question': 108, 'myocardi': 108, 'length': 108, 'molecul': 108, 'revers': 107, 'arthriti': 107, 'describ': 107, 'antidepress': 107, 'clear': 106, 'gas': 106, 'ib': 106, 'oliv': 106, 'under': 105, 'grow': 105, 'ingredi': 105, 'match': 105, 'onset': 105, 'statin': 104, 'grapefruit': 104, 'appli': 104, 'volum': 104, 'offer': 104, 'potent': 104, 'comprehens': 104, 'accept': 104, 'dha': 104, 'monitor': 104, 'systol': 104, 'longitudin': 104, 'fecal': 104, 'fractur': 103, 'irrit': 103, 'imag': 103, 'die': 102, 'reflect': 102, 'medlin': 102, 'pharmacolog': 102, 'peroxid': 102, 'infarct': 102, 'advic': 102, 'kg/m': 102, 'china': 102, 'mood': 102, 'pcbs': 102, 'difficil': 102, 'virus': 102, 'beta': 101, 'phosphat': 101, 'context': 101, 'center': 101, 'isoflavon': 101, 'market': 101, 'cadmium': 101, 'warrant': 100, 'faecal': 100, 'prior': 100, 'circumfer': 100, 'definit': 100, 'bmaa': 100, 'population-bas': 99, 'school': 99, 'chines': 99, 'remov': 99, 'act': 99, 'malign': 99, 'class': 99, 'sulforaphan': 99, 'delay': 98, 'extent': 98, 'phip': 98, 'fed': 98, 'polyunsatur': 98, 'carcinoma': 98, 'choic': 97, 'address': 97, 'administ': 97, 'great': 97, 'child': 97, 'salmonella': 97, 'pd': 97, 'invas': 97, 'unclear': 96, 'variat': 96, 'tertil': 96, 'hypothes': 96, 'avoid': 96, 'adhes': 96, 'ra': 96, 'unknown': 95, 'hand': 95, 'institut': 95, 'smoker': 95, 'yield': 95, 'folat': 95, 'met': 94, 'exert': 94, 'patholog': 94, 'pilot': 94, 'chain': 94, 'techniqu': 94, 'dental': 94, 'infus': 94, 'primarili': 93, 'suscept': 93, 'morbid': 93, 'glycem': 93, 'take': 93, 'detail': 93, 'waist': 93, 'acrylamid': 93, 'hpv': 93, 'highlight': 92, 'flow': 92, 'recogn': 92, 'gastric': 92, 'japan': 92, 'good': 92, 'lymphocyt': 92, 'eye': 92, 'homocystein': 92, 'numer': 92, 'dioxin': 92, 'high-fat': 92, 'induct': 91, 'herbal': 91, 'side': 91, 'cochran': 91, 'longer': 91, 'low-dens': 91, 'close': 91, 'aggreg': 91, 'annual': 91, 'acn': 91, 'maximum': 90, 'constitu': 90, 'harman': 90, 'equival': 90, 'powder': 90, 'resid': 90, 'underw': 90, 'la': 90, 'potassium': 90, 'store': 90, 'inhibitori': 89, 'occurr': 89, 'repeat': 89, 'exclud': 89, 'endogen': 89, 'semen': 89, 'strawberri': 89, 'attenu': 88, 'ulcer': 88, 'biochem': 88, 'featur': 88, 'erectil': 88, 'ten': 88, 'cardiac': 88, 'usual': 88, 'enrol': 88, 'ros': 88, 'capsul': 87, 'neurolog': 87, 'releas': 87, 'digest': 87, 'histolog': 87, 'fluid': 87, 'steroid': 87, 'solubl': 87, 'ascorb': 87, 'multivitamin': 87, 'arsenic': 87, 'cis': 87, 'exceed': 86, 'aspect': 86, 'bioactiv': 86, 'hydrogen': 86, 'plaqu': 86, 'short': 86, 'awar': 86, 'divers': 86, 'cigarett': 86, 'pcos': 86, 'note': 86, 'mg/kg': 86, 'goal': 86, 'occup': 86, 'snack': 86, 'util': 85, 'fri': 85, 'predictor': 85, 'testosteron': 85, 'led': 85, 'suffici': 85, 'carcinogenesi': 85, 'mushroom': 85, 'genotox': 85, 'seafood': 85, 'label': 85, 'mehg': 84, 'visual': 84, 'slight': 84, 'typic': 84, 'japanes': 84, 'rare': 84, 'methodolog': 84, 'epitheli': 84, 'elimin': 84, 'power': 84, 'interview': 84, 'hdl': 84, 'nurs': 83, 'nausea': 83, 'inclus': 83, 'rheumatoid': 83, 'success': 83, 'nuclear': 83, 'antigen': 83, 'sprout': 83, 'dilat': 82, 'half': 82, 'microm': 82, 'spice': 82, 'gender': 82, 'scienc': 82, 'microbiota': 82, 'grape': 82, 'chees': 81, 'stone': 81, 'epidem': 81, 'optim': 81, 'methionin': 81, 'igf-i': 81, 'tumour': 81, 'walnut': 81, 'mother': 80, 'absorb': 80, 'solut': 80, 'profession': 80, 'reason': 80, 'upper': 80, 'color': 80, 'phthalat': 80, 'mental': 80, 'cluster': 80, 'mrsa': 80, 'mammalian': 80, 'prenat': 79, 'failur': 79, 'appar': 79, 'regist': 79, 'self-report': 79, 'kinas': 79, 'bread': 79, 'updat': 79, 'slow': 79, 'experienc': 78, 'liquid': 78, 'antimicrobi': 78, 'c-reactiv': 78, 'larger': 78, 'predomin': 78, 'pregnant': 78, 'alpha': 78, 'ct': 78, 'cinnamon': 78, 'memori': 78, 'behaviour': 78, 'rise': 78, 'age-rel': 78, 'dark': 78, 'spectrometri': 77, 'ferment': 77, 'usa': 77, 'project': 77, 'nitrat': 77, 'anxieti': 77, 'popular': 76, 'uniqu': 76, 'calor': 76, 'formul': 76, 'modest': 76, 'visit': 76, 'locat': 76, 'mcf': 76, 'hair': 76, 'neuron': 76, 'regard': 75, 'flow-medi': 75, 'absenc': 75, 'chemoprevent': 75, 'counsel': 75, 'suppli': 75, 'contact': 75, 'retail': 75, 'interpret': 75, 'ala': 75, 'temperatur': 75, 'cm': 75, 'econom': 75, 'ischem': 75, 'short-term': 74, 'peak': 74, 'metal': 74, 'reach': 74, 'introduct': 74, 'episod': 74, 'transcript': 74, 'bladder': 74, 'prescrib': 73, 'girl': 73, 'univers': 73, 'manner': 73, 'amin': 73, 'effici': 73, 'rectal': 73, 'sedentari': 73, 'precursor': 73, 'pollut': 73, 'electron': 73, 'agricultur': 73, 'harm': 73, 'bile': 73, 'oxal': 72, 'rest': 72, 'equal': 72, 'percept': 72, 'ng/ml': 72, 'extrem': 72, 'diagnost': 72, 'integr': 72, 'air': 72, 'ige': 72, 'gel': 72, 'pbdes': 72, 'meta-analys': 72, 'mitochondri': 72, 'ng/g': 71, 'possess': 71, 'view': 71, 'high-dens': 71, 'respect': 71, 'hundr': 71, 'inconsist': 71, 'sit': 71, 'rrs': 71, 'chromatographi': 71, 'scan': 71, 'wheat': 71, 'lean': 71, 'swine': 71, 'habitu': 70, 'se': 70, 'probabl': 70, 'embas': 70, 'storag': 70, 'effort': 70, 'procedur': 70, 'exclus': 70, 'grade': 70, 'plant-bas': 70, 'adapt': 70, 'disc': 70, 'enterolacton': 70, 'iodin': 70, 'cold': 69, 'wine': 69, 'sabdariffa': 69, 'barrier': 69, 'promis': 69, 'fact': 69, 'androgen': 69, 'replac': 69, 'transit': 69, 'parent': 69, 'transmiss': 69, 'sweeten': 69, 'parkinson': 69, 'dog': 69, 'glyphos': 69, 'heat': 68, 'herb': 68, 'hibiscus': 68, 'north': 68, 'polici': 68, 'p': 68, 'suffer': 68, 'er': 68, 'manufactur': 68, 'blueberri': 68, 'expenditur': 68, 'causal': 67, 'transport': 67, 'brachial': 67, 'cumul': 67, 'dose-respons': 67, 'prolong': 67, 'student': 67, 'phytoestrogen': 67, 'concept': 67, 'microbi': 67, 'gestat': 67, 'inhal': 67, 'diastol': 67, 'ht': 67, 'substitut': 67, 'meet': 67, 'celiac': 67, 'crohn': 67, 'hip': 67, 'dose-depend': 66, 'heavi': 66, 'ca': 66, 'perceiv': 66, 'partial': 66, 'epa': 66, 'degener': 66, 'thought': 65, 'minut': 65, 'disrupt': 65, 'endocrin': 65, 'surgeri': 65, 'protocol': 65, 'mixtur': 65, 'divid': 65, 'theori': 65, 'adequ': 65, 'parallel': 65, 'interleukin': 65, 'ovarian': 65, 'modern': 65, 'peppermint': 65, 'biopsi': 65, 'degrad': 65, 'soybean': 65, 'polychlorin': 65, 'neurodegen': 65, 'p-trend': 65, 'cholin': 65, 'tool': 64, 'compris': 64, 'controversi': 64, 'seri': 64, 'brown': 64, 'mrna': 64, 'manifest': 64, 'african': 64, 'longev': 64, 'lumbar': 64, 'california': 64, 'constitut': 64, 'bias': 63, 'methylmercuri': 63, 'nitric': 63, 'coupl': 63, 'iii': 63, 'minim': 63, 'elig': 63, 'employ': 63, 'anticanc': 63, 'regimen': 63, 'deposit': 63, 'identif': 63, 'regulatori': 63, 'tast': 63, 'mucos': 63, 'zinc': 63, 'gal': 63, 'magnitud': 62, 'allow': 62, 'field': 62, 'social': 62, 'incorpor': 62, 'cervic': 62, 'elucid': 62, 'cytotox': 62, 'increment': 62, 'spp': 62, 'weak': 61, 'mutat': 61, 'sustain': 61, 'topic': 61, 'formula': 61, 'threshold': 61, 'forc': 61, 'st': 61, 'psycholog': 61, 'year-old': 61, 'adipocyt': 61, 'rural': 61, 'matter': 61, 'abund': 61, 'autoimmun': 61, 'uric': 60, 'membran': 60, 'transfer': 60, 'start': 60, 'eros': 60, 'refin': 60, 'step': 60, 'break': 60, 'b': 60, 'quantiti': 60, 'sequenc': 60, 'pigment': 60, 'nitrit': 60, 'igfbp': 60, 'toxin': 59, 'cup': 59, 'ldl-c': 59, 'migrat': 59, 'sign': 59, 'accompani': 59, 'kcal': 59, 'basal': 59, 'begin': 59, 'particl': 59, 'bran': 59, 'thyroid': 59, 'height': 59, 'lymphoma': 59, 'menarch': 59, 'poison': 58, 'diarrhea': 58, 'surveil': 58, 'infertil': 58, 'recal': 58, 'cure': 58, 'v': 58, 'classifi': 58, 'greatest': 58, 'flora': 58, 'ascertain': 58, 'oat': 58, 'oa': 58, 'fail': 57, 'arm': 57, 'monounsatur': 57, 'earlier': 57, 'breakfast': 57

In [ ]:
query=['cancer','num','diet','increas']

In [ ]:
documents=df['2nd_column_lemmatized']
docIds=df['ID']
scores={}
i=0
for d in documents:
  score=0
  lemmas = Counter(nltk.word_tokenize(d))
 # print (lemmas)
  for t in query:
  #  print(t)
   # print(lemmas.get(t))
    if(lemmas.get(t)):
      score=score+lemmas.get(t)
  id=docIds[i]
  scores[id]=score
  i=i+1

In [ ]:
def get_top_5(dictionary):
    # Sort the dictionary items based on values in descending order
    sorted_items = sorted(dictionary.items(), key=lambda x: x[1], reverse=True)

    # Return the top 5 items
    return sorted_items[0:5]

top_5 = get_top_5(scores)
print(top_5)

[('MED-1193', 145), ('MED-2082', 112), ('MED-2468', 105), ('MED-5080', 98), ('MED-2211', 95)]

In [ ]:
queries = pd.read_csv('/content/drive/MyDrive/NLP/queries.csv')
queries

             PID                                         PLAIN
0       PLAIN-10           how contaminated are our children ?
1      PLAIN-100  cancer and the animal-to-plant protein ratio
2     PLAIN-1000                                   daniel fast
3     PLAIN-1002                                dark chocolate
4     PLAIN-1003                                     dark meat
...          ...                                           ...
2589   PLAIN-993                                     cyclamate
2590   PLAIN-994                                       cycling
2591   PLAIN-995                                 cysticercosis
2592   PLAIN-998                                         dairy
2593   PLAIN-999                                     dandelion

[2594 rows x 2 columns]

In [ ]:
queries['lemmatized']=queries['PLAIN'].apply(lambda x: ' '.join([Word(word).lemmatize() for word in x.split()]))
queries

,PID,PLAIN,lemmatized
0,PLAIN-10,how contaminated are our children ?,how contaminated are our child ?
1,PLAIN-100,cancer and the animal-to-plant protein ratio,cancer and the animal-to-plant protein ratio
2,PLAIN-1000,daniel fast,daniel fast
3,PLAIN-1002,dark chocolate,dark chocolate
4,PLAIN-1003,dark meat,dark meat
...,...,...,...
2589,PLAIN-993,cyclamate,cyclamate
2590,PLAIN-994,cycling,cycling
2591,PLAIN-995,cysticercosis,cysticercosis
2592,PLAIN-998,dairy,dairy
2593,PLAIN-999,dandelion,dandelion

In [ ]:
qlist=[]
docId=[]
queriesList=queries['lemmatized']
documents=df['2nd_column_lemmatized']
docIds=df['ID']
scores={}
i=0
iteration=0
for q in queriesList:
  query=nltk.word_tokenize(q)
  for d in documents:
    score=0
    lemmas = Counter(nltk.word_tokenize(d))
  # print (lemmas)
    for t in query:
    #  print(t)
    # print(lemmas.get(t))
      if(lemmas.get(t)):
        score=score+lemmas.get(t)
    id=docIds[i]
    scores[id]=score
    i=i+1
  sc = '|'.join(map(str, [top[1] for top in get_top_5(scores)]))
  id=result_string = '|'.join([top[0] for top in get_top_5(scores)])
  qlist.append(sc)
  docId.append(id)
  print(sc)
  i=0
  print(iteration)
  iteration=iteration+1
  #if(iteration>5): break

15|15|14|14|14
0
21|20|19|17|17
1
18|11|10|6|4
2
21|18|18|17|12
3
16|14|14|12|12
4
20|15|14|14|14
5
19|17|13|11|11
6

KeyboardInterrupt:

In [ ]:
print(qlist)
print(docId)

['15|15|14|14|14', '21|20|19|17|17', '18|11|10|6|4', '21|18|18|17|12', '16|14|14|12|12', '20|15|14|14|14', '19|17|13|11|11', '18|16|11|11|10', '8|4|3|3|2', '16|14|14|12|12', '16|14|14|12|12', '3|2|2|2|2', '19|12|10|10|9', '2|1|1|1|0', '26|15|13|13|12', '18|12|11|8|8', '10|6|6|2|2', '0|0|0|0|0', '20|14|14|13|13', '2|0|0|0|0', '1|1|1|0|0', '3|2|2|2|1', '10|6|4|4|3', '3|2|2|1|1', '0|0|0|0|0', '15|15|14|14|14', '8|8|8|7|7', '8|8|8|7|7', '14|1|1|1|1', '5|4|2|1|0', '9|1|1|1|0', '1|0|0|0|0', '14|14|14|12|11', '31|27|23|23|23', '2|2|2|2|2', '8|1|0|0|0', '2|1|0|0|0', '7|5|5|4|4', '2|1|0|0|0', '1|0|0|0|0', '0|0|0|0|0', '0|0|0|0|0', '21|20|20|18|17', '1|1|0|0|0', '0|0|0|0|0', '3|2|1|1|1', '3|2|1|1|1', '0|0|0|0|0', '25|22|22|21|21', '2|1|0|0|0', '0|0|0|0|0', '0|0|0|0|0', '0|0|0|0|0', '0|0|0|0|0', '9|8|8|7|7', '22|17|14|11|11', '6|1|1|1|0', '23|17|15|11|11', '16|15|15|14|11', '16|15|15|14|9', '16|15|15|14|9', '16|11|10|10|9', '10|9|8|7|6', '0|0|0|0|0', '3|3|3|2|1', '10|9|9|8|7', '14|10|10|8|7', '26|13|12|12|12', '18|9|8|8|7', '16|14|13|12|12', '15|15|14|14|14', '16|15|13|12|12', '0|0|0|0|0', '9|5|5|5|3', '0|0|0|0|0', '18|18|17|15|15', '3|3|2|2|2', '15|14|11|10|10', '15|14|11|10|10', '0|0|0|0|0', '16|15|12|12|12', '15|14|11|10|10', '6|5|5|5|4', '6|6|5|5|5', '12|6|5|5|4', '25|19|16|15|15', '3|1|0|0|0', '21|7|6|5|5', '24|19|19|17|16', '26|13|12|12|12', '3|2|1|0|0', '0|0|0|0|0', '3|2|2|1|1', '1|0|0|0|0', '6|3|3|3|3', '2|1|1|1|0', '17|15|12|11|10', '13|11|9|9|8', '5|4|3|3|3', '11|9|8|7|6', '6|5|5|5|5', '20|15|14|14|13', '10|7|6|6|5', '4|4|3|2|1', '8|7|6|0|0', '21|19|19|17|16', '3|2|2|2|2', '26|13|12|12|12', '16|5|5|4|4', '16|9|7|7|6', '3|2|2|1|1', '4|3|3|2|2', '16|15|15|14|9', '3|3|3|2|2', '15|14|11|9|9', '15|11|11|10|10', '5|4|2|0|0', '0|0|0|0|0', '7|5|4|3|2', '17|14|13|13|11', '26|14|13|12|12', '8|4|2|1|1', '16|14|14|12|12', '34|28|14|14|13', '10|9|8|8|7', '8|8|7|6|6', '2|1|1|1|1', '29|20|18|17|15', '14|13|13|11|10', '3|3|3|2|2', '16|13|11|11|11', '7|7|6|4|4', '18|17|13|13|13', '10|6|6|6|6', '9|6|6|5|5', '9|6|5|5|5', '12|9|6|5|5', '13|11|11|10|8', '18|18|17|16|16', '14|8|7|7|6', '18|18|17|15|15', '3|2|2|2|2', '5|3|2|2|1', '18|12|11|10|10', '17|15|14|13|13', '2|0|0|0|0', '4|3|3|3|3', '20|16|15|15|15', '0|0|0|0|0', '3|1|1|0|0', '17|17|17|13|12', '24|19|18|17|17', '17|17|17|13|12', '0|0|0|0|0', '7|5|5|4|4', '27|24|24|24|24', '9|3|3|3|1', '9|9|9|8|7', '17|11|8|8|6', '6|6|5|4|4', '0|0|0|0|0', '0|0|0|0|0', '7|4|3|3|2', '3|3|1|0|0', '15|14|12|11|9', '10|6|2|2|1', '0|0|0|0|0', '28|21|18|18|17', '18|18|17|16|15', '18|18|17|15|15', '18|18|17|15|15', '18|18|17|15|15', '15|13|10|10|10', '13|10|9|8|7', '8|8|7|7|7', '2|2|1|1|0', '0|0|0|0|0', '2|2|1|0|0', '20|15|15|14|13', '5|2|2|1|1', '11|4|4|4|3', '12|5|4|4|2', '2|0|0|0|0', '15|11|11|10|10', '15|11|11|10|10', '22|21|21|20|18', '19|16|15|13|13', '4|3|2|2|2', '0|0|0|0|0', '4|2|2|1|0', '3|2|2|2|1', '16|13|11|8|8', '17|11|11|11|11', '26|13|12|12|12', '5|5|2|2|2', '13|10|9|8|7', '0|0|0|0|0', '12|11|11|7|7', '14|10|6|5|0', '12|5|5|5|4', '12|7|6|5|5', '15|11|11|10|10', '26|13|12|12|12', '16|4|2|2|1', '1|1|1|1|1', '8|6|6|5|5', '20|18|15|14|14', '0|0|0|0|0', '9|7|5|4|3', '16|9|7|6|2', '7|1|1|0|0', '9|9|7|7|7', '1|0|0|0|0', '12|10|10|8|8', '2|2|1|0|0', '2|0|0|0|0', '4|1|0|0|0', '15|15|15|14|14', '11|10|8|7|6', '2|0|0|0|0', '9|8|6|6|5', '11|8|8|7|6', '1|0|0|0|0', '22|18|12|11|11', '13|13|11|2|1', '20|10|9|9|7', '22|14|14|14|12', '28|14|14|13|13', '18|11|9|9|7', '17|11|11|11|11', '16|14|12|11|11', '0|0|0|0|0', '6|4|4|3|3', '2|2|2|1|1', '15|12|11|11|9', '21|20|16|15|15', '15|9|8|7|7', '0|0|0|0|0', '18|18|17|17|15', '0|0|0|0|0', '1|1|0|0|0', '11|9|7|6|6', '4|4|3|1|1', '9|8|7|7|6', '6|1|0|0|0', '0|0|0|0|0', '26|13|12|12|12', '9|8|8|8|6', '1|0|0|0|0', '13|6|5|3|1', '12|2|2|2|2', '16|13|9|5|4', '1|0|0|0|0', '15|11|11|10|10', '13|11|10|8|7', '2|1|0|0|0', '1|1|0|0|0', '5|4|3|2|2', '27|14|14|13|13', '4|3|0|0|0', '17|16|14|14|12', '7|6|4|4|3', '7|5|4|4|4', '8|7|6|3|3', '21|17|14|12|12', '21|17|14|12|12', '9|8|8|6|6', '27|17|14|14|13', '13|11|9|9|8', '0|0|0|0|0', '14|14|10|9|5', '26|25|24|24|24', '2|1|1|1|1', '0|0|0|0|0', '0|0|0|0|0', '9|8|6|4|4', '9|8|8|6|6', '0|0|0|0|0', '15|9|6|5|5', '28|22|22|21|21', '16|15|14|13|12', '7|5|1|0|0', '1|1|0|0|0', '17|11|10|9|9', '8|4|2|0|0', '8|8|6|6|6', '2|1|1|1|1', '2|1|0|0|0', '5|5|5|3|3', '16|14|13|13|12', '18|16|16|14|12', '5|2|1|1|1', '0|0|0|0|0', '2|1|0|0|0', '16|14|13|12|12', '4|4|0|0|0', '10|10|9|8|8', '12|11|11|7|7', '2|1|1|1|0', '16|14|13|12|12', '10|8|7|7|6', '3|0|0|0|0', '10|9|8|8|8', '20|6|4|4|4', '15|14|11|11|10', '16|11|11|10|10', '17|11|11|11|11', '14|11|11|10|10', '14|13|13|11|10', '0|0|0|0|0', '8|8|7|6|6', '20|15|14|13|12', '10|9|6|1|1', '1|0|0|0|0', '1|0|0|0|0', '11|5|3|1|1', '12|6|5|4|2', '15|15|14|14|14', '19|9|7|7|7', '30|22|18|17|17', '31|28|28|22|22', '16|15|15|14|9', '0|0|0|0|0', '20|16|15|14|13', '13|3|1|1|1', '5|5|3|2|2', '0|0|0|0|0', '2|0|0|0|0', '14|13|13|12|11', '11|7|7|5|4', '22|16|13|12|11', '13|12|9|9|8', '8|7|5|3|2', '5|5|5|4|4', '20|19|19|17|13', '4|2|2|2|2', '21|19|19|17|16', '17|9|1|1|1', '12|7|4|4|3', '16|14|12|12|10', '3|2|2|1|1', '20|15|14|14|13', '0|0|0|0|0', '5|5|4|3|3', '26|13|12|12|12', '0|0|0|0|0', '0|0|0|0|0', '2|1|1|1|1', '14|13|13|13|12', '33|27|12|12|12', '5|4|4|3|3', '2|2|1|1|1', '0|0|0|0|0', '26|19|13|7|7', '16|14|13|12|12', '1|1|0|0|0', '12|11|11|7|7', '1|0|0|0|0', '3|3|2|2|2', '17|11|11|11|11', '26|13|12|12|12', '13|11|9|8|7', '0|0|0|0|0', '0|0|0|0|0', '5|5|5|5|1', '16|14|14|12|12', '18|5|5|5|4', '2|0|0|0|0', '5|0|0|0|0', '33|28|27|19|17', '8|5|5|5|5', '4|0|0|0|0', '22|19|19|18|16', '19|15|14|13|11', '12|11|10|8|5', '12|11|10|9|9', '26|14|13|13|12', '28|19|16|11|8', '18|18|16|16|16', '0|0|0|0|0', '2|2|1|1|1', '1|0|0|0|0', '16|14|14|13|12', '2|2|2|2|2', '0|0|0|0|0', '5|4|4|4|3', '4|3|2|0|0', '20|18|14|14|12', '25|16|15|15|14', '3|2|2|1|1', '11|9|7|6|6', '7|3|1|1|1', '25|16|15|15|14', '17|17|15|15|14', '12|7|7|5|5', '2|2|2|1|1', '22|18|18|16|15', '8|7|7|6|5', '8|7|7|6|6', '9|9|8|8|7', '10|5|3|2|2', '0|0|0|0|0', '18|16|15|15|15', '12|11|8|7|6', '0|0|0|0|0', '5|5|3|2|2', '22|10|9|9|9', '7|5|4|1|1', '2|2|2|2|1', '8|7|4|4|3', '4|2|0|0|0', '6|1|0|0|0', '15|12|7|7|7', '5|4|3|3|3', '12|11|9|9|9', '6|6|5|5|5', '12|11|11|7|7', '3|1|0|0|0', '0|0|0|0|0', '0|0|0|0|0', '0|0|0|0|0', '3|3|2|1|0', '0|0|0|0|0', '10|6|6|6|5', '5|2|1|1|1', '11|9|9|9|8', '11|11|9|9|8', '26|13|12|12|12', '11|9|9|9|8', '2|2|2|2|2', '7|4|4|4|4', '5|4|4|4|4', '19|18|17|17|16', '0|0|0|0|0', '20|19|19|19|16', '18|11|9|9|9', '15|12|11|8|8', '1|1|1|1|1', '21|20|20|19|18', '19|12|11|11|11', '26|13|13|12|12', '11|6|5|5|2', '1|1|1|1|1', '11|10|8|3|2', '21|20|18|17|16', '22|11|11|10|9', '17|14|11|10|9', '12|12|12|12|11', '27|14|14|13|13', '1|1|1|1|1', '7|6|6|5|5', '17|12|11|11|11', '5|0|0|0|0', '13|11|11|10|8', '3|0|0|0|0', '2|1|0|0|0', '2|1|1|1|0', '10|3|3|3|2', '1|1|1|0|0', '4|3|0|0|0', '5|4|3|2|2', '12|10|10|10|9', '19|18|17|17|16', '1|1|1|1|0', '0|0|0|0|0', '3|2|2|1|1', '0|0|0|0|0', '10|3|2|1|0', '8|7|7|5|1', '13|8|7|7|7', '0|0|0|0|0', '0|0|0|0|0', '5|4|3|3|3', '15|5|5|5|4', '16|14|14|12|12', '16|14|14|12|12', '16|14|14|12|12', '0|0|0|0|0', '9|8|8|7|7', '8|8|6|6|5', '1|0|0|0|0', '9|8|7|6|5', '7|6|3|2|0', '19|17|16|16|16', '29|26|25|21|19', '19|4|1|1|1', '16|13|11|10|9', '12|11|11|7|7', '11|10|10|9|9', '32|17|15|15|15', '14|9|9|8|4', '8|1|0|0|0', '2|1|1|1|1', '2|1|1|1|0', '26|15|13|12|12', '13|13|11|11|9', '6|6|3|2|1', '24|21|21|19|19', '6|5|5|5|5', '14|12|12|11|11', '1|0|0|0|0', '6|6|5|5|4', '0|0|0|0|0', '5|4|3|2|2', '4|3|2|2|2', '15|12|11|8|7', '1|1|1|1|1', '7|7|5|4|4', '4|2|2|2|1', '0|0|0|0|0', '19|14|13|10|10', '7|1|0|0|0', '0|0|0|0|0', '1|1|0|0|0', '12|11|8|8|6', '18|17|16|13|12', '1|1|0|0|0', '6|5|5|5|5', '2|1|0|0|0', '0|0|0|0|0', '2|2|1|1|0', '0|0|0|0|0', '1|0|0|0|0', '2|1|0|0|0', '2|0|0|0|0', '14|14|14|14|11', '0|0|0|0|0', '9|8|7|7|6', '16|14|14|12|12', '5|4|4|3|2', '8|7|3|0|0', '7|4|4|2|1', '5|1|1|0|0', '11|11|7|6|6', '11|10|9|8|7', '5|0|0|0|0', '6|1|1|1|0', '12|9|8|8|6', '7|6|6|6|4', '17|15|11|7|7', '10|9|9|8|8', '15|10|10|9|8', '14|13|10|10|9', '10|10|9|9|8', '13|11|9|9|8', '20|9|8|7|7', '6|5|5|5|5', '8|8|8|6|6', '6|5|5|4|4', '21|21|19|19|19', '25|16|15|15|14', '1|0|0|0|0', '26|13|12|12|12', '5|1|1|1|1', '2|1|1|0|0', '1|1|1|0|0', '2|0|0|0|0', '21|19|19|17|16', '10|9|8|8|7', '12|10|10|9|9', '21|19|19|19|16', '18|17|14|11|10', '9|8|8|8|8', '15|10|7|6|6', '15|10|7|6|6', '15|10|7|6|6', '9|7|7|6|6', '23|22|22|21|21', '23|18|15|14|13', '8|7|6|5|5', '10|9|7|7|6', '12|11|11|7|7', '6|1|0|0|0', '2|1|0|0|0', '26|13|12|12|12', '2|2|2|1|1', '0|0|0|0|0', '18|18|16|15|15', '4|2|2|1|1', '4|3|2|2|2', '3|0|0|0|0', '4|3|3|2|2', '18|18|18|15|15', '3|2|2|2|1', '8|2|2|1|1', '3|2|1|1|0', '12|8|5|5|4', '12|12|8|7|6', '7|6|5|4|4', '8|8|7|7|4', '0|0|0|0|0', '6|4|3|3|2', '14|11|9|6|4', '20|17|16|15|15', '15|11|11|10|10', '8|5|4|4|4', '1|1|1|1|1', '4|3|2|1|1', '7|2|2|1|0', '0|0|0|0|0', '13|12|11|9|7', '12|11|8|8|8', '11|9|7|6|6', '11|11|7|6|6', '7|4|3|3|1', '9|9|7|6|4', '1|0|0|0|0', '11|10|9|9|9', '2|0|0|0|0', '26|14|13|12|12', '0|0|0|0|0', '5|4|3|1|0', '26|25|20|16|14', '13|10|8|5|5', '29|26|25|21|19', '8|8|7|6|6', '4|4|3|2|1', '16|14|13|12|12', '18|15|14|14|14', '20|15|14|13|13', '21|20|19|17|16', '20|19|14|14|14', '10|10|7|7|6', '1|0|0|0|0', '1|1|1|0|0', '16|14|14|12|12', '20|11|9|9|8', '28|20|18|18|17', '34|27|27|25|24', '20|18|16|13|12', '2|1|1|1|0', '0|0|0|0|0', '8|4|4|4|3', '6|2|1|1|1', '2|0|0|0|0', '22|19|19|19|18', '34|26|26|26|26', '26|13|12|12|12', '2|1|0|0|0', '4|2|1|1|1', '12|12|11|11|10', '13|12|11|9|9', '4|2|2|1|1', '4|0|0|0|0', '28|15|12|11|10', '0|0|0|0|0', '9|9|9|7|6', '15|15|14|14|14', '1|0|0|0|0', '26|13|12|12|12', '25|22|20|20|19', '14|8|7|7|7', '4|2|1|1|1', '23|21|21|21|20', '20|14|14|13|13', '1|1|0|0|0', '1|1|1|1|0', '0|0|0|0|0', '4|4|3|3|3', '2|1|1|1|1', '8|2|1|0|0', '24|24|23|22|22', '3|1|1|1|1', '0|0|0|0|0', '8|7|7|6|6', '10|6|4|4|4', '8|8|8|7|7', '9|8|8|5|4', '5|2|2|1|1', '20|13|12|11|9', '4|3|2|2|2', '1|0|0|0|0', '1|0|0|0|0', '8|8|7|7|7', '21|19|19|17|16', '26|13|12|12|12', '10|8|7|6|6', '7|6|6|5|5', '24|14|14|14|13', '10|8|7|6|6', '0|0|0|0|0', '5|3|0|0|0', '17|15|14|12|11', '0|0|0|0|0', '2|2|2|1|0', '11|7|5|5|3', '20|17|15|12|11', '1|0|0|0|0', '1|1|1|1|0', '1|0|0|0|0', '11|10|5|5|5', '0|0|0|0|0', '13|0|0|0|0', '1|0|0|0|0', '12|11|11|7|6', '0|0|0|0|0', '21|21|13|12|9', '21|16|15|11|11', '5|4|4|4|2', '11|10|9|7|7', '12|12|10|9|9', '7|6|4|3|3', '7|7|1|1|1', '5|2|1|1|1', '17|16|14|12|12', '2|0|0|0|0', '13|13|1|1|1', '12|12|12|12|11', '3|2|2|2|2', '15|14|11|11|9', '12|10|5|1|0', '32|17|15|14|13', '9|7|7|6|2', '9|7|7|1|1', '5|4|4|2|1', '6|4|4|2|1', '18|13|13|10|10', '23|22|15|13|13', '15|15|14|14|14', '3|1|0|0|0', '15|14|11|10|10', '11|10|9|8|8', '4|2|1|1|1', '11|10|10|9|9', '10|7|4|1|1', '0|0|0|0|0', '11|2|2|2|1', '2|2|1|1|0', '2|1|1|1|0', '16|14|13|13|12', '5|2|1|1|1', '6|3|2|2|2', '6|6|6|6|6', '4|4|4|4|4', '4|2|2|1|1', '2|0|0|0|0', '4|3|1|1|1', '3|3|2|2|1', '22|19|18|17|17', '16|16|16|15|14', '3|0|0|0|0', '17|15|14|12|11', '12|6|6|1|1', '4|0|0|0|0', '10|10|9|9|8', '13|13|9|8|8', '17|17|16|16|16', '15|11|8|7|7', '7|7|7|6|5', '13|11|9|9|8', '9|7|7|6|5', '10|9|9|7|7', '14|13|11|10|9', '13|11|9|9|8', '11|8|7|7|7', '17|14|12|11|10', '7|2|1|1|1', '0|0|0|0|0', '13|7|6|4|3', '4|2|2|2|2', '10|8|8|8|8', '15|15|14|14|14', '0|0|0|0|0', '7|6|5|3|3', '13|10|9|9|9', '3|2|2|2|1', '22|11|10|10|9', '1|0|0|0|0', '17|11|11|11|11', '1|0|0|0|0', '12|11|8|8|8', '18|18|17|17|15', '18|17|16|16|16', '21|7|6|6|5', '5|1|0|0|0', '0|0|0|0|0', '24|24|23|22|22', '26|13|12|12|12', '1|1|1|1|1', '16|15|14|13|13', '16|15|14|13|13', '14|8|6|5|4', '7|5|5|4|4', '5|3|3|3|3', '3|1|1|1|1', '0|0|0|0|0', '6|1|1|1|1', '3|2|2|0|0', '6|5|3|3|2', '17|17|17|14|13', '8|8|6|6|6', '0|0|0|0|0', '5|2|1|1|1', '13|13|11|9|8', '5|0|0|0|0', '1|0|0|0|0', '7|6|5|3|1', '14|9|8|6|4', '3|2|2|2|0', '0|0|0|0|0', '0|0|0|0|0', '16|14|14|12|12', '8|6|1|0|0', '5|3|3|1|1', '11|9|8|6|6', '30|17|15|15|15', '4|2|2|2|1', '11|8|8|7|6', '5|4|2|2|2', '8|4|3|3|2', '18|18|17|16|15', '1|0|0|0|0', '8|2|1|1|1', '21|19|19|17|16', '26|24|21|20|19', '17|13|11|11|10', '18|17|17|16|16', '26|25|25|11|10', '16|16|13|12|12', '23|22|22|21|21', '24|18|15|14|14', '16|14|14|12|12', '26|13|12|12|12', '18|12|11|11|10', '10|8|4|2|2', '2|1|1|1|1', '14|5|5|5|5', '12|10|10|10|10', '14|7|7|7|6', '1|0|0|0|0', '1|1|1|1|0', '16|16|12|10|10', '18|17|16|12|10', '29|18|17|16|14', '17|16|15|15|14', '18|16|16|16|13', '16|14|14|13|12', '0|0|0|0|0', '2|2|2|2|1', '6|0|0|0|0', '16|14|13|12|12', '14|9|8|8|4', '3|2|0|0|0', '25|16|15|15|14', '11|9|8|5|4', '14|13|11|10|10', '6|6|6|5|3', '2|1|0|0|0', '10|8|7|7|6', '24|17|14|14|13', '9|7|7|6|6', '2|1|1|1|1', '3|1|1|0|0', '19|18|17|17|16', '17|11|10|9|9', '13|6|6|5|5', '3|0|0|0|0', '11|10|10|10|10', '11|10|10|10|10', '1|1|1|1|1', '0|0|0|0|0', '5|2|0|0|0', '2|1|0|0|0', '0|0|0|0|0', '3|2|1|1|1', '0|0|0|0|0', '10|1|1|0|0', '13|10|10|9|7', '11|0|0|0|0', '17|4|4|3|3', '0|0|0|0|0', '13|8|7|7|6', '24|14|14|13|13', '22|22|19|15|15', '8|8|6|6|6', '0|0|0|0|0', '5|3|2|2|1', '5|4|4|3|2', '6|6|6|6|5', '26|14|14|13|13', '8|8|8|6|6', '14|12|10|9|8', '26|13|12|12|12', '8|8|8|7|6', '8|7|7|6|6', '8|5|4|3|3', '24|14|14|13|13', '16|14|14|12|12', '13|11|10|9|9', '13|1|0|0|0', '4|3|3|3|2', '1|1|1|0|0', '22|10|9|9|9', '3|0|0|0|0', '2|1|0|0|0', '15|15|14|14|14', '26|13|12|12|12', '18|16|14|13|13', '21|20|19|17|16', '26|15|14|13|12', '28|22|14|11|11', '4|3|3|3|2', '0|0|0|0|0', '0|0|0|0|0', '12|10|10|9|9', '17|15|13|11|10', '0|0|0|0|0', '0|0|0|0|0', '16|14|14|12|12', '24|14|14|13|13', '10|0|0|0|0', '13|13|11|9|9', '9|3|1|1|0', '42|19|17|16|16', '9|9|8|8|7', '9|9|8|8|8', '1|0|0|0|0', '2|2|2|1|1', '4|4|3|2|2', '6|5|5|3|3', '12|10|10|10|9', '26|26|26|24|24', '28|18|14|13|12', '12|10|10|10|9', '12|9|8|6|4', '10|7|7|7|6', '12|12|12|10|9', '7|6|3|1|1', '7|7|6|6|4', '18|18|17|15|15', '30|27|24|24|24', '22|10|9|9|9', '4|3|3|2|2', '26|13|12|12|12', '5|3|3|2|2', '3|2|1|0|0', '9|8|7|5|5', '12|7|4|4|4', '0|0|0|0|0', '26|25|24|24|24', '13|9|6|6|5', '1|0|0|0|0', '8|8|6|6|6', '19|16|16|14|14', '18|9|8|8|8', '5|2|0|0|0', '12|11|11|10|8', '26|26|26|24|24', '3|2|2|1|1', '2|1|1|1|0', '25|16|15|15|14', '20|18|18|18|16', '21|20|19|18|16', '26|13|12|12|12', '5|5|5|4|4', '13|6|5|5|5', '8|7|7|7|7', '8|8|8|7|7', '11|7|7|6|6', '11|8|7|7|7', '8|8|7|6|6', '5|1|0|0|0', '30|28|21|18|18', '12|11|8|7|7', '13|12|8|8|8', '12|11|10|8|7', '13|9|7|6|5', '2|1|0|0|0', '6|2|2|2|1', '2|0|0|0|0', '17|11|10|10|9', '0|0|0|0|0', '8|8|6|6|6', '4|2|1|1|1', '0|0|0|0|0', '5|2|2|1|1', '5|4|4|3|3', '1|1|0|0|0', '5|4|4|3|3', '15|15|14|14|14', '10|5|4|4|3', '14|4|0|0|0', '1|1|1|1|0', '3|2|2|1|1', '13|9|8|7|7', '13|9|8|7|6', '1|1|0|0|0', '1|0|0|0|0', '20|19|15|15|15', '0|0|0|0|0', '3|2|2|1|1', '7|7|5|4|2', '0|0|0|0|0', '1|0|0|0|0', '2|2|1|1|1', '16|14|14|14|12', '12|6|3|2|0', '18|12|11|10|10', '9|7|6|6|5', '1|1|0|0|0', '16|14|13|12|12', '0|0|0|0|0', '4|1|1|1|1', '13|11|10|5|3', '20|19|19|18|17', '21|20|19|19|17', '26|13|12|12|12', '10|7|5|4|3', '5|0|0|0|0', '2|1|1|1|1', '17|11|10|9|9', '0|0|0|0|0', '0|0|0|0|0', '8|7|6|6|6', '2|1|0|0|0', '21|19|19|17|16', '26|13|12|12|12', '1|0|0|0|0', '1|1|1|1|1', '21|20|19|17|17', '17|11|11|11|11', '26|13|12|12|12', '8|2|2|1|1', '11|6|5|1|0', '9|9|9|5|4', '6|5|5|1|1', '22|14|13|10|9', '15|11|11|11|10', '11|10|8|7|7', '10|10|8|7|6', '2|2|0|0|0', '17|12|11|10|9', '21|19|19|17|16', '4|3|2|2|1', '0|0|0|0|0', '1|0|0|0|0', '5|4|4|3|3', '5|2|2|2|1', '3|2|1|1|0', '6|6|4|3|2', '4|2|1|1|1', '10|1|1|1|1', '15|3|2|2|2', '8|6|5|4|4', '0|0|0|0|0', '6|2|1|1|0', '13|4|2|0|0', '0|0|0|0|0', '16|14|14|12|12', '31|13|13|12|11', '13|11|9|9|9', '0|0|0|0|0', '12|6|3|2|2', '12|6|3|2|2', '12|11|8|7|7', '6|3|3|2|1', '15|15|14|14|14', '2|0|0|0|0', '20|15|14|14|13', '0|0|0|0|0', '10|6|6|5|4', '0|0|0|0|0', '4|4|3|3|2', '12|12|11|11|9', '1|1|0|0|0', '27|23|13|12|12', '2|1|0|0|0', '3|3|2|2|2', '5|5|5|4|4', '42|16|15|15|14', '18|12|12|12|9', '14|5|5|5|4', '2|2|0|0|0', '3|1|1|1|1', '1|1|1|1|1', '6|3|3|3|3', '21|19|19|17|16', '7|5|4|4|4', '26|13|12|12|12', '8|2|2|0|0', '0|0|0|0|0', '11|6|1|1|1', '22|19|19|17|16', '15|8|8|7|7', '12|10|10|10|10', '24|16|15|14|14', '17|16|16|16|15', '16|14|12|12|12', '14|14|13|11|11', '4|4|3|3|3', '6|4|2|2|1', '13|10|8|7|6', '9|8|8|7|5', '0|0|0|0|0', '0|0|0|0|0', '0|0|0|0|0', '1|1|0|0|0', '8|3|1|0|0', '1|0|0|0|0', '24|21|20|15|15', '11|6|5|2|2', '2|1|1|1|0', '5|3|2|2|2', '9|7|5|4|4', '24|21|20|15|15', '24|21|20|15|15', '24|21|20|15|15', '22|21|20|20|19', '24|21|20|15|15', '24|21|20|19|18', '24|21|20|15|15', '3|2|1|0|0', '21|19|19|17|16', '26|13|12|12|12', '7|7|4|4|3', '20|16|14|13|12', '21|19|19|17|16', '8|6|6|5|5', '1|0|0|0|0', '12|9|8|7|7', '14|8|5|5|5', '8|1|0|0|0', '14|13|10|9|7', '8|4|1|1|0', '4|4|4|3|3', '9|8|6|5|0', '9|8|8|8|6', '2|1|1|1|1', '18|13|12|12|12', '16|14|14|12|12', '10|8|4|4|3', '8|7|7|7|6', '6|5|4|3|1', '16|16|14|14|13', '23|14|13|12|12', '21|17|13|12|9', '4|4|4|4|3', '15|14|13|2|2', '16|14|13|10|9', '32|17|17|16|15', '20|20|19|18|17', '13|11|9|9|8', '10|8|8|8|8', '24|21|21|19|19', '3|3|2|2|2', '1|0|0|0|0', '4|2|1|1|1', '18|12|11|11|11', '4|3|2|1|1', '0|0|0|0|0', '0|0|0|0|0', '6|4|0|0|0', '3|2|1|1|0', '0|0|0|0|0', '6|4|4|3|3', '14|9|8|7|6', '12|12|7|6|6', '16|12|12|3|1', '3|3|3|2|2', '2|2|2|1|1', '0|0|0|0|0', '9|8|6|6|5', '14|5|5|5|4', '17|12|11|11|11', '21|19|19|19|18', '1|0|0|0|0', '2|0|0|0|0', '16|14|14|12|12', '0|0|0|0|0', '4|1|1|1|1', '3|2|0|0|0', '20|15|12|11|10', '18|12|11|11|10', '33|28|14|14|13', '16|15|15|14|14', '41|33|24|22|18', '12|10|7|7|7', '24|11|11|10|9', '24|13|13|11|11', '12|7|5|5|4', '26|17|13|13|13', '20|14|14|13|13', '15|15|14|14|14', '32|30|12|11|10', '17|17|16|15|15', '22|18|15|15|14', '18|17|15|14|13', '20|19|15|15|15', '29|21|19|15|15', '30|21|18|18|18', '28|21|19|18|17', '12|10|10|10|9', '28|21|18|18|17', '17|14|12|11|11', '44|26|26|22|22', '18|16|13|13|12', '19|17|17|16|14', '19|19|18|17|17', '16|14|14|13|12', '14|13|11|11|10', '26|23|22|22|21', '19|19|8|7|7', '20|20|17|17|17', '15|11|11|10|10', '22|18|16|15|15', '21|19|19|18|18', '14|14|9|7|5', '20|17|16|15|14', '9|7|5|4|3', '36|16|15|14|11', '33|22|17|16|15', '19|17|16|16|16', '4|2|2|2|2', '19|17|16|16|16', '21|15|15|14|12', '33|30|30|30|29', '22|17|14|12|12', '18|17|14|14|14', '18|17|17|15|15', '8|7|7|6|6', '10|10|8|8|8', '22|15|14|14|14', '22|20|15|14|14', '21|19|19|17|16', '15|15|14|14|14', '8|8|7|7|7', '17|11|8|8|8', '18|17|16|14|12', '21|17|17|15|15', '10|9|7|6|6', '5|5|5|4|4', '21|19|18|12|8', '24|22|20|16|15', '3|3|2|2|2', '22|19|18|15|13', '10|10|8|8|8', '46|29|27|27|27', '16|11|10|9|9', '18|17|16|16|16', '17|16|15|14|12', '17|16|16|16|15', '23|22|19|19|19', '17|16|15|15|15', '15|9|9|8|8', '19|11|10|6|4', '18|18|18|18|15', '17|16|15|15|15', '15|15|14|13|13', '17|16|15|13|13', '47|39|27|22|20', '18|17|14|14|13', '18|17|16|16|16', '11|10|10|9|9', '28|17|17|17|17', '30|27|27|26|26', '19|16|16|14|13', '12|12|11|11|10', '10|9|8|8|8', '12|9|7|7|6', '27|7|7|6|5', '16|15|15|10|9', '15|15|15|15|15', '17|16|15|15|15', '25|22|20|20|19', '34|27|25|24|24', '31|24|21|20|19', '16|14|13|13|12', '16|14|13|12|12', '16|15|14|13|12', '16|16|16|15|14', '17|13|11|10|9', '15|15|14|14|14', '15|15|14|14|14', '11|9|9|9|9', '17|15|13|12|11', '17|15|13|12|11', '17|12|11|11|8', '11|11|8|8|8', '17|11|11|11|11', '12|12|12|12|11', '13|11|9|9|8', '23|18|16|15|15', '16|14|14|12|12', '15|15|15|14|14', '24|21|16|14|14', '25|22|22|16|14', '9|9|9|8|8', '15|15|14|14|14', '12|11|11|10|9', '14|13|11|10|10', '16|15|14|13|12', '20|16|15|15|15', '7|5|5|5|4', '23|16|14|12|12', '26|24|24|24|24', '12|7|4|4|4', '15|15|15|14|14', '14|13|13|11|10', '13|7|6|5|5', '21|19|19|17|16', '15|15|14|14|14', '26|21|20|19|18', '16|15|15|14|14', '8|8|8|7|7', '26|18|16|11|9', '31|19|17|16|15', '25|23|18|17|17', '27|15|12|11|10', '80|62|30|29|28', '21|19|19|18|18', '22|21|21|19|19', '22|22|22|21|20', '14|10|9|8|8', '23|16|14|13|12', '8|8|7|7|6', '14|12|12|11|9', '16|11|11|10|10', '9|9|8|8|7', '9|9|8|8|7', '9|9|8|8|8', '10|9|8|8|7', '17|16|14|14|14', '16|14|14|12|12', '17|14|13|13|13', '15|14|11|10|10', '17|15|13|11|11', '14|13|13|11|10

In [ ]:
#add scores as column
queries['scores']=qlist
queries['docId']=docId
queries
#print(scores)

,PID,PLAIN,lemmatized,scores,docId
0,PLAIN-10,how contaminated are our children ?,how contaminated are our child ?,15|15|14|14|14,MED-2058|MED-3150|MED-1729|MED-4744|MED-5005
1,PLAIN-100,cancer and the animal-to-plant protein ratio,cancer and the animal-to-plant protein ratio,21|20|19|17|17,MED-1721|MED-2760|MED-3703|MED-3557|MED-3699
2,PLAIN-1000,daniel fast,daniel fast,18|11|10|6|4,MED-1617|MED-1761|MED-1620|MED-5105|MED-2646
3,PLAIN-1002,dark chocolate,dark chocolate,21|18|18|17|12,MED-2224|MED-4336|MED-5040|MED-4782|MED-5148
4,PLAIN-1003,dark meat,dark meat,16|14|14|12|12,MED-2671|MED-1802|MED-5235|MED-2584|MED-4057
...,...,...,...,...,...
2589,PLAIN-993,cyclamate,cyclamate,1|0|0|0|0,MED-4604|MED-10|MED-14|MED-118|MED-301
2590,PLAIN-994,cycling,cycling,4|2|1|1|1,MED-4506|MED-3894|MED-2716|MED-3151|MED-3796
2591,PLAIN-995,cysticercosis,cysticercosis,5|3|1|1|1,MED-3182|MED-4672|MED-3170|MED-3172|MED-3177
2592,PLAIN-998,dairy,dairy,13|9|6|6|6,MED-1773|MED-5194|MED-5192|MED-5193|MED-5196
2593,PLAIN-999,dandelion,dandelion,1|0|0|0|0,MED-4864|MED-10|MED-14|MED-118|MED-301

In [ ]:
import numpy as np
def Thresholding(value):
  if value < 0.1: return 0
  elif value < 0.3: return 1
  elif value <0.7: return 2
  else : return 3

In [ ]:
#normalize
import numpy as np

result_list=[]
for q in qlist:
  res_tem=q.split('|')
  res_tem_int=[int(element) for element in res_tem]
  result_list =result_list+res_tem_int

print(result_list)

my_min=np.min(result_list)
my_max=np.max(result_list)

result_list=3*(result_list-my_min)/(my_max-my_min)
print(np.max(result_list))

#thresholds_all=[Thresholding(r) for r in result_list]

# Group elements into sublists of 5
sublists = [result_list[i:i+5] for i in range(0, len(result_list), 5)]
# threshold_sublists=[thresholds_all[i:i+5] for i in range(0, len(thresholds_all), 5)]

# Join each sublist with '|'
scoresNormalized = ['|'.join(map(str, sublist)) for sublist in sublists]
# threshold_column=['|'.join(map(str, sublist)) for sublist in threshold_sublists]

# print(threshold_column)
queries['scoresNormalized'] = scoresNormalized
# queries['Thresholds'] = threshold_column

queries

[15, 15, 14, 14, 14, 21, 20, 19, 17, 17, 18, 11, 10, 6, 4, 21, 18, 18, 17, 12, 16, 14, 14, 12, 12, 20, 15, 14, 14, 14, 19, 17, 13, 11, 11, 18, 16, 11, 11, 10, 8, 4, 3, 3, 2, 16, 14, 14, 12, 12, 16, 14, 14, 12, 12, 3, 2, 2, 2, 2, 19, 12, 10, 10, 9, 2, 1, 1, 1, 0, 26, 15, 13, 13, 12, 18, 12, 11, 8, 8, 10, 6, 6, 2, 2, 0, 0, 0, 0, 0, 20, 14, 14, 13, 13, 2, 0, 0, 0, 0, 1, 1, 1, 0, 0, 3, 2, 2, 2, 1, 10, 6, 4, 4, 3, 3, 2, 2, 1, 1, 0, 0, 0, 0, 0, 15, 15, 14, 14, 14, 8, 8, 8, 7, 7, 8, 8, 8, 7, 7, 14, 1, 1, 1, 1, 5, 4, 2, 1, 0, 9, 1, 1, 1, 0, 1, 0, 0, 0, 0, 14, 14, 14, 12, 11, 31, 27, 23, 23, 23, 2, 2, 2, 2, 2, 8, 1, 0, 0, 0, 2, 1, 0, 0, 0, 7, 5, 5, 4, 4, 2, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 21, 20, 20, 18, 17, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 3, 2, 1, 1, 1, 3, 2, 1, 1, 1, 0, 0, 0, 0, 0, 25, 22, 22, 21, 21, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 8, 8, 7, 7, 22, 17, 14, 11, 11, 6, 1, 1, 1, 0, 23, 17, 15, 11, 11, 16, 15, 15, 14, 11, 16, 15, 15, 14, 9, 16, 15, 15, 14, 9, 16, 11, 10, 10, 9, 10, 9, 8, 7, 6, 0, 0, 0, 0, 0, 3, 3, 3, 2, 1, 10, 9, 9, 8, 7, 14, 10, 10, 8, 7, 26, 13, 12, 12, 12, 18, 9, 8, 8, 7, 16, 14, 13, 12, 12, 15, 15, 14, 14, 14, 16, 15, 13, 12, 12, 0, 0, 0, 0, 0, 9, 5, 5, 5, 3, 0, 0, 0, 0, 0, 18, 18, 17, 15, 15, 3, 3, 2, 2, 2, 15, 14, 11, 10, 10, 15, 14, 11, 10, 10, 0, 0, 0, 0, 0, 16, 15, 12, 12, 12, 15, 14, 11, 10, 10, 6, 5, 5, 5, 4, 6, 6, 5, 5, 5, 12, 6, 5, 5, 4, 25, 19, 16, 15, 15, 3, 1, 0, 0, 0, 21, 7, 6, 5, 5, 24, 19, 19, 17, 16, 26, 13, 12, 12, 12, 3, 2, 1, 0, 0, 0, 0, 0, 0, 0, 3, 2, 2, 1, 1, 1, 0, 0, 0, 0, 6, 3, 3, 3, 3, 2, 1, 1, 1, 0, 17, 15, 12, 11, 10, 13, 11, 9, 9, 8, 5, 4, 3, 3, 3, 11, 9, 8, 7, 6, 6, 5, 5, 5, 5, 20, 15, 14, 14, 13, 10, 7, 6, 6, 5, 4, 4, 3, 2, 1, 8, 7, 6, 0, 0, 21, 19, 19, 17, 16, 3, 2, 2, 2, 2, 26, 13, 12, 12, 12, 16, 5, 5, 4, 4, 16, 9, 7, 7, 6, 3, 2, 2, 1, 1, 4, 3, 3, 2, 2, 16, 15, 15, 14, 9, 3, 3, 3, 2, 2, 15, 14, 11, 9, 9, 15, 11, 11, 10, 10, 5, 4, 2, 0, 0, 0, 0, 0, 0, 0, 7, 5, 4, 3, 2, 17, 14, 13, 13, 11, 26, 14, 13, 12, 12, 8, 4, 2, 1, 1, 16, 14, 14, 12, 12, 34, 28, 14, 14, 13, 10, 9, 8, 8, 7, 8, 8, 7, 6, 6, 2, 1, 1, 1, 1, 29, 20, 18, 17, 15, 14, 13, 13, 11, 10, 3, 3, 3, 2, 2, 16, 13, 11, 11, 11, 7, 7, 6, 4, 4, 18, 17, 13, 13, 13, 10, 6, 6, 6, 6, 9, 6, 6, 5, 5, 9, 6, 5, 5, 5, 12, 9, 6, 5, 5, 13, 11, 11, 10, 8, 18, 18, 17, 16, 16, 14, 8, 7, 7, 6, 18, 18, 17, 15, 15, 3, 2, 2, 2, 2, 5, 3, 2, 2, 1, 18, 12, 11, 10, 10, 17, 15, 14, 13, 13, 2, 0, 0, 0, 0, 4, 3, 3, 3, 3, 20, 16, 15, 15, 15, 0, 0, 0, 0, 0, 3, 1, 1, 0, 0, 17, 17, 17, 13, 12, 24, 19, 18, 17, 17, 17, 17, 17, 13, 12, 0, 0, 0, 0, 0, 7, 5, 5, 4, 4, 27, 24, 24, 24, 24, 9, 3, 3, 3, 1, 9, 9, 9, 8, 7, 17, 11, 8, 8, 6, 6, 6, 5, 4, 4, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 4, 3, 3, 2, 3, 3, 1, 0, 0, 15, 14, 12, 11, 9, 10, 6, 2, 2, 1, 0, 0, 0, 0, 0, 28, 21, 18, 18, 17, 18, 18, 17, 16, 15, 18, 18, 17, 15, 15, 18, 18, 17, 15, 15, 18, 18, 17, 15, 15, 15, 13, 10, 10, 10, 13, 10, 9, 8, 7, 8, 8, 7, 7, 7, 2, 2, 1, 1, 0, 0, 0, 0, 0, 0, 2, 2, 1, 0, 0, 20, 15, 15, 14, 13, 5, 2, 2, 1, 1, 11, 4, 4, 4, 3, 12, 5, 4, 4, 2, 2, 0, 0, 0, 0, 15, 11, 11, 10, 10, 15, 11, 11, 10, 10, 22, 21, 21, 20, 18, 19, 16, 15, 13, 13, 4, 3, 2, 2, 2, 0, 0, 0, 0, 0, 4, 2, 2, 1, 0, 3, 2, 2, 2, 1, 16, 13, 11, 8, 8, 17, 11, 11, 11, 11, 26, 13, 12, 12, 12, 5, 5, 2, 2, 2, 13, 10, 9, 8, 7, 0, 0, 0, 0, 0, 12, 11, 11, 7, 7, 14, 10, 6, 5, 0, 12, 5, 5, 5, 4, 12, 7, 6, 5, 5, 15, 11, 11, 10, 10, 26, 13, 12, 12, 12, 16, 4, 2, 2, 1, 1, 1, 1, 1, 1, 8, 6, 6, 5, 5, 20, 18, 15, 14, 14, 0, 0, 0, 0, 0, 9, 7, 5, 4, 3, 16, 9, 7, 6, 2, 7, 1, 1, 0, 0, 9, 9, 7, 7, 7, 1, 0, 0, 0, 0, 12, 10, 10, 8, 8, 2, 2, 1, 0, 0, 2, 0, 0, 0, 0, 4, 1, 0, 0, 0, 15, 15, 15, 14, 14, 11, 10, 8, 7, 6, 2, 0, 0, 0, 0, 9, 8, 6, 6, 5, 11, 8, 8, 7, 6, 1, 0, 0, 0, 0, 22, 18, 12, 11, 11, 13, 13, 11, 2, 1, 20, 10, 9, 9, 7, 22, 14, 14, 14, 12, 28, 14, 14, 13, 13, 18, 11, 9, 9, 7, 17, 11, 11, 11, 11, 16, 14, 12, 11, 11, 0, 0, 0, 0, 0, 6, 4, 4, 3, 3, 2, 2, 2, 1, 1, 15, 12, 11, 11, 9, 21, 20, 16, 15, 15, 15, 9, 8, 7, 7, 0, 0, 0, 0, 0, 18, 18, 17, 17, 15, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 11, 9, 7, 6, 6, 4, 4, 3, 1, 1, 9, 8, 7, 7, 6, 6, 1, 0, 0, 0, 0, 0, 0, 0, 0, 26, 13, 12, 12, 12, 9, 8, 8, 8, 6, 1, 0, 0, 0, 0, 13, 6, 5, 3, 1, 12, 2, 2, 2, 2, 16, 13, 9, 5, 4, 1, 0, 0, 0, 0, 15, 11, 11, 10, 10, 13, 11, 10, 8, 7, 2, 1, 0, 0, 0, 1, 1, 0, 0, 0, 5, 4, 3, 2, 2, 27, 14, 14, 13, 13, 4, 3, 0, 0, 0, 17, 16, 14, 14, 12, 7, 6, 4, 4, 3, 7, 5, 4, 4, 4, 8, 7, 6, 3, 3, 21, 17, 14, 12, 12, 21, 17, 14, 12, 12, 9, 8, 8, 6, 6, 27, 17, 14, 14, 13, 13, 11, 9, 9, 8, 0, 0, 0, 0, 0, 14, 14, 10, 9, 5, 26, 25, 24, 24, 24, 2, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9, 8, 6, 4, 4, 9, 8, 8, 6, 6, 0, 0, 0, 0, 0, 15, 9, 6, 5, 5, 28, 22, 22, 21, 21, 16, 15, 14, 13, 12, 7, 5, 1, 0, 0, 1, 1, 0, 0, 0, 17, 11, 10, 9, 9, 8, 4, 2, 0, 0, 8, 8, 6, 6, 6, 2, 1, 1, 1, 1, 2, 1, 0, 0, 0, 5, 5, 5, 3, 3, 16, 14, 13, 13, 12, 18, 16, 16, 14, 12, 5, 2, 1, 1, 1, 0, 0, 0, 0, 0, 2, 1, 0, 0, 0, 16, 14, 13, 12, 12, 4, 4, 0, 0, 0, 10, 10, 9, 8, 8, 12, 11, 11, 7, 7, 2, 1, 1, 1, 0, 16, 14, 13, 12, 12, 10, 8, 7, 7, 6, 3, 0, 0, 0, 0, 10, 9, 8, 8, 8, 20, 6, 4, 4, 4, 15, 14, 11, 11, 10, 16, 11, 11, 10, 10, 17, 11, 11, 11, 11, 14, 11, 11, 10, 10, 14, 13, 13, 11, 10, 0, 0, 0, 0, 0, 8, 8, 7, 6, 6, 20, 15, 14, 13, 12, 10, 9, 6, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 11, 5, 3, 1, 1, 12, 6, 5, 4, 2, 15, 15, 14, 14, 14, 19, 9, 7, 7, 7, 30, 22, 18, 17, 17, 31, 28, 28, 22, 22, 16, 15, 15, 14, 9, 0, 0, 0, 0, 0, 20, 16, 15, 14, 13, 13, 3, 1, 1, 1, 5, 5, 3, 2, 2, 0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 14, 13, 13, 12, 11, 11, 7, 7, 5, 4, 22, 16, 13, 12, 11, 13, 12, 9, 9, 8, 8, 7, 5, 3, 2, 5, 5, 5, 4, 4, 20, 19, 19, 17, 13, 4, 2, 2, 2, 2, 21, 19, 19, 17, 16, 17, 9, 1, 1, 1, 12, 7, 4, 4, 3, 16, 14, 12, 12, 10, 3, 2, 2, 1, 1, 20, 15, 14, 14, 13, 0, 0, 0, 0, 0, 5, 5, 4, 3, 3, 26, 13, 12, 12, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 1, 1, 1, 1, 14, 13, 13, 13, 12, 33, 27, 12, 12, 12, 5, 4, 4, 3, 3, 2, 2, 1, 1, 1, 0, 0, 0, 0, 0, 26, 19, 13, 7, 7, 16, 14, 13, 12, 12, 1, 1, 0, 0, 0, 12, 11, 11, 7, 7, 1, 0, 0, 0, 0, 3, 3, 2, 2, 2, 17, 11, 11, 11, 11, 26, 13, 12, 12, 12, 13, 11, 9, 8, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 5, 5, 5, 1, 16, 14, 14, 12, 12, 18, 5, 5, 5, 4, 2, 0, 0, 0, 0, 5, 0, 0, 0, 0, 33, 28, 27, 19, 17, 8, 5, 5, 5, 5, 4, 0, 0, 0, 0, 22, 19, 19, 18, 16, 19, 15, 14, 13, 11, 12, 11, 10, 8, 5, 12, 11, 10, 9, 9, 26, 14, 13, 13, 12, 28, 19, 16, 11, 8, 18, 18, 16, 16, 16, 0, 0, 0, 0, 0, 2, 2, 1, 1, 1, 1, 0, 0, 0, 0, 16, 14, 14, 13, 12, 2, 2, 2, 2, 2, 0, 0, 0, 0, 0, 5, 4, 4, 4, 3, 4, 3, 2, 0, 0, 20, 18, 14, 14, 12, 25, 16, 15, 15, 14, 3, 2, 2, 1, 1, 11, 9, 7, 6, 6, 7, 3, 1, 1, 1, 25, 16, 15, 15, 14, 17, 17, 15, 15, 14, 12, 7, 7, 5, 5, 2, 2, 2, 1, 1, 22, 18, 18, 16, 15, 8, 7, 7, 6, 5, 8, 7, 7, 6, 6, 9, 9, 8, 8, 7, 10, 5, 3, 2, 2, 0, 0, 0, 0, 0, 18, 16, 15, 15, 15, 12, 11, 8, 7, 6, 0, 0, 0, 0, 0, 5, 5, 3, 2, 2, 22, 10, 9, 9, 9, 7, 5, 4, 1, 1, 2, 2, 2, 2, 1, 8, 7, 4, 4, 3, 4, 2, 0, 0, 0, 6, 1, 0, 0, 0, 15, 12, 7, 7, 7, 5, 4, 3, 3, 3, 12, 11, 9, 9, 9, 6, 6, 5, 5, 5, 12, 11, 11, 7, 7, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 3, 2, 1, 0, 0, 0, 0, 0, 0, 10, 6, 6, 6, 5, 5, 2, 1, 1, 1, 11, 9, 9, 9, 8, 11, 11, 9, 9, 8, 26, 13, 12, 12, 12, 11, 9, 9, 9, 8, 2, 2, 2, 2, 2, 7, 4, 4, 4, 4, 5, 4, 4, 4, 4, 19, 18, 17, 17, 16, 0, 0, 0, 0, 0, 20, 19, 19, 19, 16, 18, 11, 9, 9, 9, 15, 12, 11, 8, 8, 1, 1, 1, 1, 1, 21, 20, 20, 19, 18, 19, 12, 11, 11, 11, 26, 13, 13, 12, 12, 11, 6, 5, 5, 2, 1, 1, 1, 1, 1, 11, 10, 8, 3, 2, 21, 20, 18, 17, 16, 22, 11, 11, 10, 9, 17, 14, 11, 10, 9, 12, 12, 12, 12, 11, 27, 14, 14, 13, 13, 1, 1, 1, 1, 1, 7, 6, 6, 5, 5, 17, 12, 11, 11, 11, 5, 0, 0, 0, 0, 13, 11, 11, 10, 8, 3, 0, 0, 0, 0, 2, 1, 0, 0, 0, 2, 1, 1, 1, 0, 10, 3, 3, 3, 2, 1, 1, 1, 0, 0, 4, 3, 0, 0, 0, 5, 4, 3, 2, 2, 12, 10, 10, 10, 9, 19, 18, 17, 17, 16, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 3, 2, 2, 1, 1, 0, 0, 0, 0, 0, 10, 3, 2, 1, 0, 8, 7, 7, 5, 1, 13, 8, 7, 7, 7, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 4, 3, 3, 3, 15, 5, 5, 5, 4, 16, 14, 14, 12, 12, 16, 14, 14, 12, 12, 16, 14, 14, 12, 12, 0, 0, 0, 0, 0, 9, 8, 8, 7, 7, 8, 8, 6, 6, 5, 1, 0, 0, 0, 0, 9, 8, 7, 6, 5, 7, 6, 3, 2, 0, 19, 17, 16, 16, 16, 29, 26, 25, 21, 19, 19, 4, 1, 1, 1, 16, 13, 11, 10, 9, 12, 11, 11, 7, 7, 11, 10, 10, 9, 9, 32, 17, 15, 15, 15, 14, 9, 9, 8, 4, 8, 1, 0, 0, 0, 2, 1, 1, 1, 1, 2, 1, 1, 1, 0, 26, 15, 13, 12, 12, 13, 13, 11, 11, 9, 6, 6, 3, 2, 1, 24, 21, 21, 19, 19, 6, 5, 5, 5, 5, 14, 12, 12, 11, 11, 1, 0, 0, 0, 0, 6, 6, 5, 5, 4, 0, 0, 0, 0, 0, 5, 4, 3, 2, 2, 4, 3, 2, 2, 2, 15, 12, 11, 8, 7, 1, 1, 1, 1, 1, 7, 7, 5, 4, 4, 4, 2, 2, 2, 1, 0, 0, 0, 0, 0, 19, 14, 13, 10, 10, 7, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 12, 11, 8, 8, 6, 18, 17, 16, 13, 12, 1, 1, 0, 0, 0, 6, 5, 5, 5, 5, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 2, 2, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 1, 0, 0, 0, 2, 0, 0, 0, 0, 14, 14, 14, 14, 11, 0, 0, 0, 0, 0, 9, 8, 7, 7, 6, 16, 14, 14, 12, 12, 5, 4, 4, 3, 2, 8, 7, 3, 0, 0, 7, 4, 4, 2, 1, 5, 1, 1, 0, 0, 11, 11, 7, 6, 6, 11, 10, 9, 8, 7, 5, 0, 0, 0, 0, 6, 1, 1, 1, 0, 12, 9, 8, 8, 6, 7, 6, 6, 6, 4, 17, 15, 11, 7, 7, 10, 9, 9, 8, 8, 15, 10, 10, 9, 8, 14, 13, 10, 10, 9, 10, 10, 9, 9, 8, 13, 11, 9, 9, 8, 20, 9, 8, 7, 7, 6, 5, 5, 5, 5, 8, 8, 8, 6, 6, 6, 5, 5, 4, 4, 21, 21, 19, 19, 19, 25, 16, 15, 15, 14, 1, 0, 0, 0, 0, 26, 13, 12, 12, 12, 5, 1, 1, 1, 1, 2, 1, 1, 0, 0, 1, 1, 1, 0, 0, 2, 0, 0, 0, 0, 21, 19, 19, 17, 16, 10, 9, 8, 8, 7, 12, 10, 10, 9, 9, 21, 19, 19, 19, 16, 18, 17, 14, 11, 10, 9, 8, 8, 8, 8, 15, 10, 7, 6, 6, 15, 10, 7, 6, 6, 15, 10, 7, 6, 6, 9, 7, 7, 6, 6, 23, 22, 22, 21, 21, 23, 18, 15, 14, 13, 8, 7, 6, 5, 5, 10, 9, 7, 7, 6, 12, 11, 11, 7, 7, 6, 1, 0, 0, 0, 2, 1, 0, 0, 0, 26, 13, 12, 12, 12, 2, 2, 2, 1, 1, 0, 0, 0, 0, 0, 18, 18, 16, 15, 15, 4, 2, 2, 1, 1, 4, 3, 2, 2, 2, 3, 0, 0, 0, 0, 4, 3, 3, 2, 2, 18, 18, 18, 15, 15, 3, 2, 2, 2, 1, 8, 2, 2, 1, 1, 3, 2, 1, 1, 0, 12, 8, 5, 5, 4, 12, 12, 8, 7, 6, 7, 6, 5, 4, 4, 8, 8, 7, 7, 4, 0, 0, 0, 0, 0, 6, 4, 3, 3, 2, 14, 11, 9, 6, 4, 20, 17, 16, 15, 15, 15, 11, 11, 10, 10, 8, 5, 4, 4, 4, 1, 1, 1, 1, 1, 4, 3, 2, 1, 1, 7, 2, 2, 1, 0, 0, 0, 0, 0, 0, 13, 12, 11, 9, 7, 12, 11, 8, 8, 8, 11, 9, 7, 6, 6, 11, 11, 7, 6, 6, 7, 4, 3, 3, 1, 9, 9, 7, 6, 4, 1, 0, 0, 0, 0, 11, 10, 9, 9, 9, 2, 0, 0, 0, 0, 26, 14, 13, 12, 12, 0, 0, 0, 0, 0, 5, 4, 3, 1, 0, 26, 25, 20, 16, 14, 13, 10, 8, 5, 5, 29, 26, 25, 21, 19, 8, 8, 7, 6, 6, 4, 4, 3, 2, 1, 16, 14, 13, 12, 12, 18, 15, 14, 14, 14, 20, 15, 14, 13, 13, 21, 20, 19, 17, 16, 20, 19, 14, 14, 14, 10, 10, 7, 7, 6, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 16, 14, 14, 12, 12, 20, 11, 9, 9, 8, 28, 20, 18, 18, 17, 34, 27, 27, 25, 24, 20, 18, 16, 13, 12, 2, 1, 1, 1, 0, 0, 0, 0, 0, 0, 8, 4, 4, 4, 3, 6, 2, 1, 1, 1, 2, 0, 0, 0, 0, 22, 19, 19, 19, 18, 34, 26, 26, 26, 26, 26, 13, 12, 12, 12, 2, 1, 0, 0, 0, 4, 2, 1, 1, 1, 12, 12, 11, 11, 10, 13, 12, 11, 9, 9, 4, 2, 2, 1, 1, 4, 0, 0, 0, 0, 28, 15, 12, 11, 10, 0, 0, 0, 0, 0, 9, 9, 9, 7, 6, 15, 15, 14, 14, 14, 1, 0, 0, 0, 0, 26, 13, 12, 12, 12, 25, 22, 20, 20, 19, 14, 8, 7, 7, 7, 4, 2, 1, 1, 1, 23, 21, 21, 21, 20, 20, 14, 14, 13, 13, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 4, 4, 3, 3, 3, 2, 1, 1, 1, 1, 8, 2, 1, 0, 0, 24, 24, 23, 22, 22, 3, 1, 1, 1, 1, 0, 0, 0, 0, 0, 8, 7, 7, 6, 6, 10, 6, 4, 4, 4, 8, 8, 8, 7, 7, 9, 8, 8, 5, 4, 5, 2, 2, 1, 1, 20, 13, 12, 11, 9, 4, 3, 2, 2, 2, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 8, 8, 7, 7, 7, 21, 19, 19, 17, 16, 26, 13, 12, 12, 12, 10, 8, 7, 6, 6, 7, 6, 6, 5, 5, 24, 14, 14, 14, 13, 10, 8, 7, 6, 6, 0, 0, 0, 0, 0, 5, 3, 0, 0, 0, 17, 15, 14, 12, 11, 0, 0, 0, 0, 0, 2, 2, 2, 1, 0, 11, 7, 5, 5, 3, 20, 17, 15, 12, 11, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 11, 10, 5, 5, 5, 0, 0, 0, 0, 0, 13, 0, 0, 0, 0, 1, 0, 0, 0, 0, 12, 11, 11, 7, 6, 0, 0, 0, 0, 0, 21, 21, 13, 12, 9, 21, 16, 15, 11, 11, 5, 4, 4, 4, 2, 11, 10, 9, 7, 7, 12, 12, 10, 9, 9, 7, 6, 4, 3, 3, 7, 7, 1, 1, 1, 5, 2, 1, 1, 1, 17, 16, 14, 12, 12, 2, 0, 0, 0, 0, 13, 13, 1, 1, 1, 12, 12, 12, 12, 11, 3, 2, 2, 2, 2, 15, 14, 11, 11, 9, 12, 10, 5, 1, 0, 32, 17, 15, 14, 13, 9, 7, 7, 6, 2, 9, 7, 7, 1, 1, 5, 4, 4, 2, 1, 6, 4, 4, 2, 1, 18, 13, 13, 10, 10, 23, 22, 15, 13, 13, 15, 15, 14, 14, 14, 3, 1, 0, 0, 0, 15, 14, 11, 10, 10, 11, 10, 9, 8, 8, 4, 2, 1, 1, 1, 11, 10, 10, 9, 9, 10, 7, 4, 1, 1, 0, 0, 0, 0, 0, 11, 2, 2, 2, 1, 2, 2, 1, 1, 0, 2, 1, 1, 1, 0, 16, 14, 13, 13, 12, 5, 2, 1, 1, 1, 6, 3, 2, 2, 2, 6, 6, 6, 6, 6, 4, 4, 4, 4, 4, 4, 2, 2, 1, 1, 2, 0, 0, 0, 0, 4, 3, 1, 1, 1, 3, 3, 2, 2, 1, 22, 19, 18, 17, 17, 16, 16, 16, 15, 14, 3, 0, 0, 0, 0, 17, 15, 14, 12, 11, 12, 6, 6, 1, 1, 4, 0, 0, 0, 0, 10, 10, 9, 9, 8, 13, 13, 9, 8, 8, 17, 17, 16, 16, 16, 15, 11, 8, 7, 7, 7, 7, 7, 6, 5, 13, 11, 9, 9, 8, 9, 7, 7, 6, 5, 10, 9, 9, 7, 7, 14, 13, 11, 10, 9, 13, 11, 9, 9, 8, 11, 8, 7, 7, 7, 17, 14, 12, 11, 10, 7, 2, 1, 1, 1, 0, 0, 0, 0, 0, 13, 7, 6, 4, 3, 4, 2, 2, 2, 2, 10, 8, 8, 8, 8, 15, 15, 14, 14, 14, 0, 0, 0, 0, 0, 7, 6, 5, 3, 3, 13, 10, 9, 9, 9, 3, 2, 2, 2, 1, 22, 11, 10, 10, 9, 1, 0, 0, 0, 0, 17, 11, 11, 11, 11, 1, 0, 0, 0, 0, 12, 11, 8, 8, 8, 18, 18, 17, 17, 15, 18, 17, 16, 16, 16, 21, 7, 6, 6, 5, 5, 1, 0, 0, 0, 0, 0, 0, 0, 0, 24, 24, 23, 22, 22, 26, 13, 12, 12, 12, 1, 1, 1, 1, 1, 16, 15, 14, 13, 13, 16, 15, 14, 13, 13, 14, 8, 6, 5, 4, 7, 5, 5, 4, 4, 5, 3, 3, 3, 3, 3, 1, 1, 1, 1, 0, 0, 0, 0, 0, 6, 1, 1, 1, 1, 3, 2, 2, 0, 0, 6, 5, 3, 3, 2, 17, 17, 17, 14, 13, 8, 8, 6, 6, 6, 0, 0, 0, 0, 0, 5, 2, 1, 1, 1, 13, 13, 11, 9, 8, 5, 0, 0, 0, 0, 1, 0, 0, 0, 0, 7, 6, 5, 3, 1, 14, 9, 8, 6, 4, 3, 2, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 14, 14, 12, 12, 8, 6, 1, 0, 0, 5, 3, 3, 1, 1, 11, 9, 8, 6, 6, 30, 17, 15, 15, 15, 4, 2, 2, 2, 1, 11, 8, 8, 7, 6, 5, 4, 2, 2, 2, 8, 4, 3, 3, 2, 18, 18, 17, 16, 15, 1, 0, 0, 0, 0, 8, 2, 1, 1, 1, 21, 19, 19, 17, 16, 26, 24, 21, 20, 19, 17, 13, 11, 11, 10, 18, 17, 17, 16, 16, 26, 25, 25, 11, 10, 16, 16, 13, 12, 12, 23, 22, 22, 21, 21, 24, 18, 15, 14, 14, 16, 14, 14, 12, 12, 26, 13, 12, 12, 12, 18, 12, 11, 11, 10, 10, 8, 4, 2, 2, 2, 1, 1, 1, 1, 14, 5, 5, 5, 5, 12, 10, 10, 10, 10, 14, 7, 7, 7, 6, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 16, 16, 12, 10, 10, 18, 17, 16, 12, 10, 29, 18, 17, 16, 14, 17, 16, 15, 15, 14, 18, 16, 16, 16, 13, 16, 14, 14, 13, 12, 0, 0, 0, 0, 0, 2, 2, 2, 2, 1, 6, 0, 0, 0, 0, 16, 14, 13, 12, 12, 14, 9, 8, 8, 4, 3, 2, 0, 0, 0, 25, 16, 15, 15, 14, 11, 9, 8, 5, 4, 14, 13, 11, 10, 10, 6, 6, 6, 5, 3, 2, 1, 0, 0, 0, 10, 8, 7, 7, 6, 24, 17, 14, 14, 13, 9, 7, 7, 6, 6, 2, 1, 1, 1, 1, 3, 1, 1, 0, 0, 19, 18, 17, 17, 16, 17, 11, 10, 9, 9, 13, 6, 6, 5, 5, 3, 0, 0, 0, 0, 11, 10, 10, 10, 10, 11, 10, 10, 10, 10, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 5, 2, 0, 0, 0, 2, 1, 0, 0, 0, 0, 0, 0, 0, 0, 3, 2, 1, 1, 1, 0, 0, 0, 0, 0, 10, 1, 1, 0, 0, 13, 10, 10, 9, 7, 11, 0, 0, 0, 0, 17, 4, 4, 3, 3, 0, 0, 0, 0, 0, 13, 8, 7, 7, 6, 24, 14, 14, 13, 13, 22, 22, 19, 15, 15, 8, 8, 6, 6, 6, 0, 0, 0, 0, 0, 5, 3, 2, 2, 1, 5, 4, 4, 3, 2, 6, 6, 6, 6, 5, 26, 14, 14, 13, 13, 8, 8, 8, 6, 6, 14, 12, 10, 9, 8, 26, 13, 12, 12, 12, 8, 8, 8, 7, 6, 8, 7, 7, 6, 6, 8, 5, 4, 3, 3, 24, 14, 14, 13, 13, 16, 14, 14, 12, 12, 13, 11, 10, 9, 9, 13, 1, 0, 0, 0, 4, 3, 3, 3, 2, 1, 1, 1, 0, 0, 22, 10, 9, 9, 9, 3, 0, 0, 0, 0, 2, 1, 0, 0, 0, 15, 15, 14, 14, 14, 26, 13, 12, 12, 12, 18, 16, 14, 13, 13, 21, 20, 19, 17, 16, 26, 15, 14, 13, 12, 28, 22, 14, 11, 11, 4, 3, 3, 3, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 12, 10, 10, 9, 9, 17, 15, 13, 11, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 14, 14, 12, 12, 24, 14, 14, 13, 13, 10, 0, 0, 0, 0, 13, 13, 11, 9, 9, 9, 3, 1, 1, 0, 42, 19, 17, 16, 16, 9, 9, 8, 8, 7, 9, 9, 8, 8, 8, 1, 0, 0, 0, 0, 2, 2, 2, 1, 1, 4, 4, 3, 2, 2, 6, 5, 5, 3, 3, 12, 10, 10, 10, 9, 26, 26, 26, 24, 24, 28, 18, 14, 13, 12, 12, 10, 10, 10, 9, 12, 9, 8, 6, 4, 10, 7, 7, 7, 6, 12, 12, 12, 10, 9, 7, 6, 3, 1, 1, 7, 7, 6, 6, 4, 18, 18, 17, 15, 15, 30, 27, 24, 24, 24, 22, 10, 9, 9, 9, 4, 3, 3, 2, 2, 26, 13, 12, 12, 12, 5, 3, 3, 2, 2, 3, 2, 1, 0, 0, 9, 8, 7, 5, 5, 12, 7, 4, 4, 4, 0, 0, 0, 0, 0, 26, 25, 24, 24, 24, 13, 9, 6, 6, 5, 1, 0, 0, 0, 0, 8, 8, 6, 6, 6, 19, 16, 16, 14, 14, 18, 9, 8, 8, 8, 5, 2, 0, 0, 0, 12, 11, 11, 10, 8, 26, 26, 26, 24, 24, 3, 2, 2, 1, 1, 2, 1, 1, 1, 0, 25, 16, 15, 15, 14, 20, 18, 18, 18, 16, 21, 20, 19, 18, 16, 26, 13, 12, 12, 12, 5, 5, 5, 4, 4, 13, 6, 5, 5, 5, 8, 7, 7, 7, 7, 8, 8, 8, 7, 7, 11, 7, 7, 6, 6, 11, 8, 7, 7, 7, 8, 8, 7, 6, 6, 5, 1, 0, 0, 0, 30, 28, 21, 18, 18, 12, 11, 8, 7, 7, 13, 12, 8, 8, 8, 12, 11, 10, 8, 7, 13, 9, 7, 6, 5, 2, 1, 0, 0, 0, 6, 2, 2, 2, 1, 2, 0, 0, 0, 0, 17, 11, 10, 10, 9, 0, 0, 0, 0, 0, 8, 8, 6, 6, 6, 4, 2, 1, 1, 1, 0, 0, 0, 0, 0, 5, 2, 2, 1, 1, 5, 4, 4, 3, 3, 1, 1, 0, 0, 0, 5, 4, 4, 3, 3, 15, 15, 14, 14, 14, 10, 5, 4, 4, 3, 14, 4, 0, 0, 0, 1, 1, 1, 1, 0, 3, 2, 2, 1, 1, 13, 9, 8, 7, 7, 13, 9, 8, 7, 6, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 20, 19, 15, 15, 15, 0, 0, 0, 0, 0, 3, 2, 2, 1, 1, 7, 7, 5, 4, 2, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 2, 2, 1, 1, 1, 16, 14, 14, 14, 12, 12, 6, 3, 2, 0, 18, 12, 11, 10, 10, 9, 7, 6, 6, 5, 1, 1, 0, 0, 0, 16, 14, 13, 12, 12, 0, 0, 0, 0, 0, 4, 1, 1, 1, 1, 13, 11, 10, 5, 3, 20, 19, 19, 18, 17, 21, 20, 19, 19, 17, 26, 13, 12, 12, 12, 10, 7, 5, 4, 3, 5, 0, 0, 0, 0, 2, 1, 1, 1, 1, 17, 11, 10, 9, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 7, 6, 6, 6, 2, 1, 0, 0, 0, 21, 19, 19, 17, 16, 26, 13, 12, 12, 12, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 21, 20, 19, 17, 17, 17, 11, 11, 11, 11, 26, 13, 12, 12, 12, 8, 2, 2, 1, 1, 11, 6, 5, 1, 0, 9, 9, 9, 5, 4, 6, 5, 5, 1, 1, 22, 14, 13, 10, 9, 15, 11, 11, 11, 10, 11, 10, 8, 7, 7, 10, 10, 8, 7, 6, 2, 2, 0, 0, 0, 17, 12, 11, 10, 9, 21, 19, 19, 17, 16, 4, 3, 2, 2, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 5, 4, 4, 3, 3, 5, 2, 2, 2, 1, 3, 2, 1, 1, 0, 6, 6, 4, 3, 2, 4, 2, 1, 1, 1, 10, 1, 1, 1, 1, 15, 3, 2, 2, 2, 8, 6, 5, 4, 4, 0, 0, 0, 0, 0, 6, 2, 1, 1, 0, 13, 4, 2, 0, 0, 0, 0, 0, 0, 0, 16, 14, 14, 12, 12, 31, 13, 13, 12, 11, 13, 11, 9, 9, 9, 0, 0, 0, 0, 0, 12, 6, 3, 2, 2, 12, 6, 3, 2, 2, 12, 11, 8, 7, 7, 6, 3, 3, 2, 1, 15, 15, 14, 14, 14, 2, 0, 0, 0, 0, 20, 15, 14, 14, 13, 0, 0, 0, 0, 0, 10, 6, 6, 5, 4, 0, 0, 0, 0, 0, 4, 4, 3, 3, 2, 12, 12, 11, 11, 9, 1, 1, 0, 0, 0, 27, 23, 13, 12, 12, 2, 1, 0, 0, 0, 3, 3, 2, 2, 2, 5, 5, 5, 4, 4, 42, 16, 15, 15, 14, 18, 12, 12, 12, 9, 14, 5, 5, 5, 4, 2, 2, 0, 0, 0, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 6, 3, 3, 3, 3, 21, 19, 19, 17, 16, 7, 5, 4, 4, 4, 26, 13, 12, 12, 12, 8, 2, 2, 0, 0, 0, 0, 0, 0, 0, 11, 6, 1, 1, 1, 22, 19, 19, 17, 16, 15, 8, 8, 7, 7, 12, 10, 10, 10, 10, 24, 16, 15, 14, 14, 17, 16, 16, 16, 15, 16, 14, 12, 12, 12, 14, 14, 13, 11, 11, 4, 4, 3, 3, 3, 6, 4, 2, 2, 1, 13, 10, 8, 7, 6, 9, 8, 8, 7, 5, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 8, 3, 1, 0, 0, 1, 0, 0, 0, 0, 24, 21, 20, 15, 15, 11, 6, 5, 2, 2, 2, 1, 1, 1, 0, 5, 3, 2, 2, 2, 9, 7, 5, 4, 4, 24, 21, 20, 15, 15, 24, 21, 20, 15, 15, 24, 21, 20, 15, 15, 22, 21, 20, 20, 19, 24, 21, 20, 15, 15, 24, 21, 20, 19, 18, 24, 21, 20, 15, 15, 3, 2, 1, 0, 0, 21, 19, 19, 17, 16, 26, 13, 12, 12, 12, 7, 7, 4, 4, 3, 20, 16, 14, 13, 12, 21, 19, 19, 17, 16, 8, 6, 6, 5, 5, 1, 0, 0, 0, 0, 12, 9, 8, 7, 7, 14, 8, 5, 5, 5, 8, 1, 0, 0, 0, 14, 13, 10, 9, 7, 8, 4, 1, 1, 0, 4, 4, 4, 3, 3, 9, 8, 6, 5, 0, 9, 8, 8, 8, 6, 2, 1, 1, 1, 1, 18, 13, 12, 12, 12, 16, 14, 14, 12, 12, 10, 8, 4, 4, 3, 8, 7, 7, 7, 6, 6, 5, 4, 3, 1, 16, 16, 14, 14, 13, 23, 14, 13, 12, 12, 21, 17, 13, 12, 9, 4, 4, 4, 4, 3, 15, 14, 13, 2, 2, 16, 14, 13, 10, 9, 32, 17, 17, 16, 15, 20, 20, 19, 18, 17, 13, 11, 9, 9, 8, 10, 8, 8, 8, 8, 24, 21, 21, 19, 19, 3, 3, 2, 2, 2, 1, 0, 0, 0, 0, 4, 2, 1, 1, 1, 18, 12, 11, 11, 11, 4, 3, 2, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 4, 0, 0, 0, 3, 2, 1, 1, 0, 0, 0, 0, 0, 0, 6, 4, 4, 3, 3, 14, 9, 8, 7, 6, 12, 12, 7, 6, 6, 16, 12, 12, 3, 1, 3, 3, 3, 2, 2, 2, 2, 2, 1, 1, 0, 0, 0, 0, 0, 9, 8, 6, 6, 5, 14, 5, 5, 5, 4, 17, 12, 11, 11, 11, 21, 19, 19, 19, 18, 1, 0, 0, 0, 0, 2, 0, 0, 0, 0, 16, 14, 14, 12, 12, 0, 0, 0, 0, 0, 4, 1, 1, 1, 1, 3, 2, 0, 0, 0, 20, 15, 12, 11, 10, 18, 12, 11, 11, 10, 33, 28, 14, 14, 13, 16, 15, 15, 14, 14, 41, 33, 24, 22, 18, 12, 10, 7, 7, 7, 24, 11, 11, 10, 9, 24, 13, 13, 11, 11, 12, 7, 5, 5, 4, 26, 17, 13, 13, 13, 20, 14, 14, 13, 13, 15, 15, 14, 14, 14, 32, 30, 12, 11, 10, 17, 17, 16, 15, 15, 22, 18, 15, 15, 14, 18, 17, 15, 14, 13, 20, 

,PID,PLAIN,lemmatized,scores,docId,scoresNormalized,Thresholds
0,PLAIN-10,how contaminated are our children ?,how contaminated are our child ?,15|15|14|14|14,MED-2058|MED-3150|MED-1729|MED-4744|MED-5005,0.1875|0.1875|0.175|0.175|0.175,1|1|1|1|1
1,PLAIN-100,cancer and the animal-to-plant protein ratio,cancer and the animal-to-plant protein ratio,21|20|19|17|17,MED-1721|MED-2760|MED-3703|MED-3557|MED-3699,0.2625|0.25|0.2375|0.2125|0.2125,1|1|1|1|1
2,PLAIN-1000,daniel fast,daniel fast,18|11|10|6|4,MED-1617|MED-1761|MED-1620|MED-5105|MED-2646,0.225|0.1375|0.125|0.075|0.05,1|1|1|0|0
3,PLAIN-1002,dark chocolate,dark chocolate,21|18|18|17|12,MED-2224|MED-4336|MED-5040|MED-4782|MED-5148,0.2625|0.225|0.225|0.2125|0.15,1|1|1|1|1
4,PLAIN-1003,dark meat,dark meat,16|14|14|12|12,MED-2671|MED-1802|MED-5235|MED-2584|MED-4057,0.2|0.175|0.175|0.15|0.15,1|1|1|1|1
...,...,...,...,...,...,...,...
2589,PLAIN-993,cyclamate,cyclamate,1|0|0|0|0,MED-4604|MED-10|MED-14|MED-118|MED-301,0.0125|0.0|0.0|0.0|0.0,0|0|0|0|0
2590,PLAIN-994,cycling,cycling,4|2|1|1|1,MED-4506|MED-3894|MED-2716|MED-3151|MED-3796,0.05|0.025|0.0125|0.0125|0.0125,0|0|0|0|0
2591,PLAIN-995,cysticercosis,cysticercosis,5|3|1|1|1,MED-3182|MED-4672|MED-3170|MED-3172|MED-3177,0.0625|0.0375|0.0125|0.0125|0.0125,0|0|0|0|0
2592,PLAIN-998,dairy,dairy,13|9|6|6|6,MED-1773|MED-5194|MED-5192|MED-5193|MED-5196,0.1625|0.1125|0.075|0.075|0.075,1|1|0|0|0
2593,PLAIN-999,dandelion,dandelion,1|0|0|0|0,MED-4864|MED-10|MED-14|MED-118|MED-301,0.0125|0.0|0.0|0.0|0.0,0|0|0|0|0

In [ ]:
max_value = queries['scores'].max()
print(max_value)

9|9|9|8|8

In [ ]:
queries.describe()

,PID,PLAIN,lemmatized,scores,docId,scoresNormalized,Thresholds
count,2594,2594,2594,2594,2594,2594,2594
unique,2594,2580,2576,1366,1878,1366,18
top,PLAIN-10,eating green to prevent cancer,dioxin,0|0|0|0|0,MED-10|MED-14|MED-118|MED-301|MED-306,0.0|0.0|0.0|0.0|0.0,1|1|1|1|1
freq,1,2,2,147,147,147,985

#Count documents for relation for each query

In [ ]:
import pandas as pd
relations = pd.read_csv('/content/drive/MyDrive/NLP/train3_2_1.csv')
relations

In [ ]:

def count_documents_for_relation(pid):
    query_result = relations[relations['PID'] == pid]
    count_by_relation = query_result['Relation'].value_counts().sort_index()
    return count_by_relation


relationCount=[]
for pid in relations['PID']:
  c=count_documents_for_relation(pid)
  relationCount.append(c)
  print(c)

2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
2    60
3     5
Name: Relation, dtype: int64
1    22
3     3
Name: Relation, dtype: int64
1    22
3     3
Name: Relation, dtype: int64
1    22
3     3
Name: Relation, dtype: int64
1    22
3     3
Name: Relation, dtype: int64
1    22
3     3
Name: Relation, dtype: int64
1    22
3     3
Name: Relation, dtype: int64
1    22
3     3
Name: Relation, dtype: int64
1    22
3     3
Name: Relation, dtype: int64
1    22
3     3
Name: Relation, dtype: int64
1    22
3     3
Name: Relation, dtype: int64
1    22
3     3
Name: Relation, dtype: int64
1    22
3     3
Name: Relation, dtype: int64
1    22
3     3
Name: Relation, dtype: int64
1    22
3     3
Name: Relation, dtype: int64
1    22
3     3
Name: Relation, dtype: int64
1    22
3     3
Name: Relation, dtype: int64
1    22
3     3
Name: Relation, dtype: int64
1    22
3     3
Name: Relation, dtype: int64
1    22
3     3
Name: Relation, dtype: int64
1    22
3     3
Name: Relation, dtype: int64
1    22
3     3
Name: Relation, dtype: int64
1    22
3     3
Name: Relation, dtype: int64
1    22
3     3
Name: Relation, dtype: int64
1    22
3     3
Name: Relation, dtype: int64
1    22
3     3
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    76
3     7
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    57
3     5
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    76
3    11
Name: Relation, dtype: int64
2    21
3     2
Name: Relation, dtype: int64
2    21
3     2
Name: Relation, dtype: int64
2    21
3     2
Name: Relation, dtype: int64
2    21
3     2
Name: Relation, dtype: int64
2    21
3     2
Name: Relation, dtype: int64
2    21
3     2
Name: Relation, dtype: int64
2    21
3     2
Name: Relation, dtype: int64
2    21
3     2
Name: Relation, dtype: int64
2    21
3     2
Name: Relation, dtype: int64
2    21
3     2
Name: Relation, dtype: int64
2    21
3     2
Name: Relation, dtype: int64
2    21
3     2
Name: Relation, dtype: int64
2    21
3     2
Name: Relation, dtype: int64
2    21
3     2
Name: Relation, dtype: int64
2    21
3     2
Name: Relation, dtype: int64
2    21
3     2
Name: Relation, dtype: int64
2    21
3     2
Name: Relation, dtype: int64
2    21
3     2
Name: Relation, dtype: int64
2    21
3     2
Name: Relation, dtype: int64
2    21
3     2
Name: Relation, dtype: int64
2    21
3     2
Name: Relation, dtype: int64
2    21
3     2
Name: Relation, dtype: int64
2    21
3     2
Name: Relation, dtype: int64
2    23
3     3
Name: Relation, dtype: int64
2    23
3     3
Name: Relation, dtype: int64
2    23
3     3
Name: Relation, dtype: int64
2    23
3     3
Name: Relation, dtype: int64
2    23
3     3
Name: Relation, dtype: int64
2    23
3     3
Name: Relation, dtype: int64
2    23
3     3
Name: Relation, dtype: int64
2    23
3     3
Name: Relation, dtype: int64
2    23
3     3
Name: Relation, dtype: int64
2    23
3     3
Name: Relation, dtype: int64
2    23
3     3
Name: Relation, dtype: int64
2    23
3     3
Name: Relation, dtype: int64
2    23
3     3
Name: Relation, dtype: int64
2    23
3     3
Name: Relation, dtype: int64
2    23
3     3
Name: Relation, dtype: int64
2    23
3     3
Name: Relation, dtype: int64
2    23
3     3
Name: Relation, dtype: int64
2    23
3     3
Name: Relation, dtype: int64
2    23
3     3
Name: Relation, dtype: int64
2    23
3     3
Name: Relation, dtype: int64
2    23
3     3
Name: Relation, dtype: int64
2    23
3     3
Name: Relation, dtype: int64
2    23
3     3
Name: Relation, dtype: int64
2    23
3     3
Name: Relation, dtype: int64
2    23
3     3
Name: Relation, dtype: int64
2    23
3     3
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5
Name: Relation, dtype: int64
2    74
3     5

KeyboardInterrupt:

In [ ]:
average_by_relation = relationUndersampled.groupby('Relation')['PID'].count() //relationUndersampled['PID'].nunique()
print(average_by_relation)

##Undersampling

In [ ]:
columns = ['PID', 'DocID', 'Relation']
relationUndersampled = pd.DataFrame(columns=columns)
# c=r['DocID']
# print(c)

for index, row in relations.iterrows():
  print(index)
  if row['DocID'] in undersampled_df['ID'].tolist():
     relationUndersampled.loc[len(relationUndersampled)] = [row['PID'], row['DocID'], row['Relation']]

NameError: name 'relations' is not defined

#hgtrhfghfh

In [ ]:
relationUndersampled

              PID     DocID  Relation
0         PLAIN-3  MED-2435         2
1         PLAIN-3  MED-3846         2
2         PLAIN-3  MED-3850         2
3         PLAIN-3  MED-4445         2
4         PLAIN-3  MED-5323         2
...           ...       ...       ...
21197  PLAIN-3474  MED-2917         2
21198  PLAIN-3474  MED-3019         2
21199  PLAIN-3474  MED-3540         2
21200  PLAIN-3474  MED-3546         2
21201  PLAIN-3474  MED-4633         2

[21202 rows x 3 columns]

In [ ]:
undersampled_df.to_csv('/content/drive/MyDrive/NLP/DocuentsUndersampled.csv', index=False)
relationUndersampled.to_csv('/content/drive/MyDrive/NLP/RelationsUndersampled.csv', index=False)

In [ ]:
relations

               PID     DocID  Relation
0          PLAIN-3  MED-2436         3
1          PLAIN-3  MED-2437         3
2          PLAIN-3  MED-2438         3
3          PLAIN-3  MED-2439         3
4          PLAIN-3  MED-2440         3
...            ...       ...       ...
139345  PLAIN-3474  MED-3546         2
139346  PLAIN-3474  MED-3547         2
139347  PLAIN-3474  MED-4632         2
139348  PLAIN-3474  MED-4633         2
139349  PLAIN-3474  MED-4634         2

[139350 rows x 3 columns]

In [ ]:
average_by_relation = relationUndersampled.groupby('Relation')['PID'].count() //relationUndersampled['PID'].nunique()
print(average_by_relation)

Relation
1    2
2    7
3    0
Name: PID, dtype: int64

In [ ]:

expected=[]
it=0
for index, row in queries.iterrows():
  d_ids=row.docId
  d_ids_list=d_ids.split('|')
  qid=row.PID

  for d in d_ids_list:
    filtered_rows = relations[(relations['PID'] == qid) & (relations['DocID'] ==d)].Relation.tolist()
    if(len(filtered_rows)!=0):
      r=filtered_rows[0]
      expected.append(r)
      print(r)
    else:
      expected.append(0)

  it=it+1
print(expected)

2
2
2
2
1
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
3
2
2
2
2
2
2
3
2
3
2
2
2
2
2
2
3
2
2
2
2
2
2
2
2
2
2
3
2
2
2
2
1
2
1
2
3
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
3
2
2
2
2
2
1
2
2
2
2
2
2
2
3
3
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
2
3
2
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
1
1
2
2
2
2
2
3
2
2
2
2
2
3
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
2
2
2
2
2
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
1
1
1
3
3
2
2
2
2
2
2
2
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
2
2
2
2
2
2
2
2
2
2
2
3
2
2
2
2
1
2
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
1
2
2
1
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
2
2
2
1
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
1
2
1
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
1
2
2
2
2
2
2
2
2
2
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
1
1
2
1
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
3
3
3
3
3
3
3
3
3
3
2
3
3
2
3
3
3
3
3
3
2
2
3
3
3
3
3
2
2
2
3
3
3
3
3
2
2
3
3
3
3
2
3
3
2
3
3
2
2
3
3
3
3
3
1
2
3
3
3
2
3
3
2
2
3
3
3
3
3
3
3
3
3
2
3
2
3
3
2
3
3
3
3
3
3
3
3
3
3
3
3
2
2
2
2
3
3
3
3
1
2
2
3
3
3
3
3
3
3
2
3
3
3
2
3
3
3
2
2
2
3
3
3
2
2
3
2
2
3
3
3
2
2
3
3
3
3
3
2
3
3
3
2
3
2
3
2
3
3
3
3
3
3
3
3
3
3
2
3
3
2
2
3
3
2
2
3
3
2
3
3
3
3
3
3
3
3
2
2
2
2
2
3
3
3
2
2
3
1
1
3
3
2
2
3
3
3
3
3
3
3
3
3
3
3
3
3
3
2
2
3
2
2
2
3
3
3
2
3
3
3
2
2
2
3
3
3
2
3
3
3
3
3
3
3
3
3
3
3
2
2
2
3
3
2
2
2
3
3
3
3
3
3
3
3
3
3
3
3
3
2
3
2
3
3
3
2
3
3
3
3
3
3
2
3
3
3
3
3
3
3
3
2
3
3
2
2
3
3
3
3
3
3
3
3
3
3
3
2
3
3
1
2
3
3
3
2
3
2
2
3
2
3
3
3
3
3
3
3
3
3
3
2
3
3
3
2
3
3
3
3
3
2
3
3
2
3
3
2
3
3
2
3
2
3
3
3
3
3
3
2
2
2
3
2
3
3
3
3
3
3
3
3
3
3
3
3
3
2
2
2
2
3
2
3
3
3
2
3
2
2
3
2
3
2
3
3
3
2
3
3
3
3
3
3
2
3
3
3
3
2
3
2
1
2
2
2
2
2
2
2
2
3
3
3
2
2
2
1
1
2
3
2
3
1
3
2
3
3
2
3
1
2
3
3
3
3
3
2
3
1
1
1
3
2
3
1
3
3
1
1
1
3
3
3
2
1
2
2
3
3
3
3
3
3
3
3
3
2
3
3
3
2
2
3
1
1
2
3
3
2
3
2
3
3
3
2
3
2
3
3
2
1
1
3
1
3
2
3
2
2
3
3
1
3
1
3
2
3
3
3
3
3
3
3
2
3
3
3
3
3
1
3
1
1
1
1
3
3
3
1
1
3
2
2
2
3
3
1
1
3
3
3
2
3
2
2
2
2
3
3
2
2
2
2
2
2
2
3
3
2
2
3
3
2
2
2
2
3
3
3
3
3
2
3
3
3
2
2
2
2
2
3
1
3
2
2
3
2
3
2
3
2
2
2
3
2
2
3
2
2
1
1
2
2
2
3
3
2
3
3
2
2
2
2
3
3
3
2
3
2
2
1
2
3
3
3
2
2
2
3
2
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
3
2
2
1
2
2
3
2
2
2
3
2
2
2
2
2
2
2
2
2
3
2
2
3
3
2
2
2
3
2
2
3
3
2
2
2
2
2
2
2
3
2
2
1
2
2
2
3
2
2
2
2
2
3
2
3
3
2
3
2
2
2
2
2
2
3
3
2
2
2
2
2
2
3
2
2
2
2
2
2
2
3
2
2
3
2
3
2
3
2
2
3
2
2
2
2
3
3
2
2
2
2
2
2
2
2
2
2
2
2
3
2
3
2
3
2
2
2
2
2
2
3
2
3
2
2
2
3
2
3
3
3
2
2
3
3
2
2
3
2
2
2
2
3
2
2
2
3
2
2
3
3
3
3
3
3
3
3
2
2
3
3
3
3
3
2
2
3
3
2
2
2
3
3
3
3
3
3
3
2
2
2
2
2
2
2
2
2
3
2
3
2
3
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
3
2
2
2
2
2
2
2
1
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
1
2
1
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
1
2
1
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
3
2
2
2
2
2
2
2
2
2
2
2
3
2
2
2
2
2
2
2
2
2
3
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
3
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
2
1
2
1
1
1
2
2
2
2
2
2

In [ ]:
expected_sublists=[expected[i:i+5] for i in range(0, len(expected), 5)]
expected_column=['|'.join(map(str, sublist)) for sublist in expected_sublists]
queries['expected'] = expected_column
queries

,PID,PLAIN,lemmatized,scores,docId,scoresNormalized,Thresholds,expected
0,PLAIN-10,how contaminated are our children ?,how contaminated are our child ?,15|15|14|14|14,MED-2058|MED-3150|MED-1729|MED-4744|MED-5005,0.1875|0.1875|0.175|0.175|0.175,1|1|1|1|1,0|0|0|0|0
1,PLAIN-100,cancer and the animal-to-plant protein ratio,cancer and the animal-to-plant protein ratio,21|20|19|17|17,MED-1721|MED-2760|MED-3703|MED-3557|MED-3699,0.2625|0.25|0.2375|0.2125|0.2125,1|1|1|1|1,0|0|0|0|2
2,PLAIN-1000,daniel fast,daniel fast,18|11|10|6|4,MED-1617|MED-1761|MED-1620|MED-5105|MED-2646,0.225|0.1375|0.125|0.075|0.05,1|1|1|0|0,0|0|0|0|0
3,PLAIN-1002,dark chocolate,dark chocolate,21|18|18|17|12,MED-2224|MED-4336|MED-5040|MED-4782|MED-5148,0.2625|0.225|0.225|0.2125|0.15,1|1|1|1|1,2|0|2|0|2
4,PLAIN-1003,dark meat,dark meat,16|14|14|12|12,MED-2671|MED-1802|MED-5235|MED-2584|MED-4057,0.2|0.175|0.175|0.15|0.15,1|1|1|1|1,0|0|0|1|1
...,...,...,...,...,...,...,...,...
2589,PLAIN-993,cyclamate,cyclamate,1|0|0|0|0,MED-4604|MED-10|MED-14|MED-118|MED-301,0.0125|0.0|0.0|0.0|0.0,0|0|0|0|0,0|0|0|0|0
2590,PLAIN-994,cycling,cycling,4|2|1|1|1,MED-4506|MED-3894|MED-2716|MED-3151|MED-3796,0.05|0.025|0.0125|0.0125|0.0125,0|0|0|0|0,2|0|0|0|0
2591,PLAIN-995,cysticercosis,cysticercosis,5|3|1|1|1,MED-3182|MED-4672|MED-3170|MED-3172|MED-3177,0.0625|0.0375|0.0125|0.0125|0.0125,0|0|0|0|0,1|2|1|1|1
2592,PLAIN-998,dairy,dairy,13|9|6|6|6,MED-1773|MED-5194|MED-5192|MED-5193|MED-5196,0.1625|0.1125|0.075|0.075|0.075,1|1|0|0|0,2|2|2|2|2
2593,PLAIN-999,dandelion,dandelion,1|0|0|0|0,MED-4864|MED-10|MED-14|MED-118|MED-301,0.0125|0.0|0.0|0.0|0.0,0|0|0|0|0,2|0|0|0|0

In [ ]:
queries.to_csv('/content/drive/MyDrive/NLP/queriesNew.csv', index=False)

In [ ]:
def distance(x, y):
  eval_values = [0, 0.1, 0.5, 0.75, 1]
  if (x == y):
    return eval_values[4]
  elif(x - y < -1 ):
    return eval_values[0]
  elif(x - y > 1):
    return eval_values[1]
  elif(x - y == -1):
    return eval_values[2]
  elif(x - y == 1):
    return eval_values[3]

In [ ]:
def resScore(res, exp):
  scores = []
  for i in range(len(res)):
    scores.append(abs(res[i]-exp[i]))
  return np.mean(scores)

In [ ]:
measure=[]
it=0
for index, row in queries.iterrows():
  res=row.Thresholds
  exp=row.expected
  res_list=res.split('|')
  exp_list=exp.split('|')
  res_list=[int(element) for element in res_list]
  exp_list=[int(element) for element in exp_list]
  measure.append(resScore(res_list,exp_list))

print(measure)
queries['measure'] = measure

[0.75, 0.7, 0.85, 0.6, 0.85, 0.75, 0.65, 0.5, 0.5, 0.75, 0.75, 1.0, 0.6, 1.0, 0.52, 0.55, 0.5, 1.0, 0.55, 0.8, 0.8, 1.0, 0.7, 0.6, 1.0, 0.75, 0.85, 0.5, 0.7, 1.0, 0.95, 1.0, 0.55, 0.65, 0.4, 0.7, 0.8, 1.0, 1.0, 1.0, 1.0, 1.0, 0.75, 1.0, 1.0, 1.0, 1.0, 1.0, 0.47000000000000003, 0.8, 1.0, 1.0, 1.0, 1.0, 0.7, 0.75, 0.8, 0.65, 0.75, 0.75, 0.75, 0.6, 0.7, 1.0, 0.6, 0.45, 0.45, 0.62, 0.8, 0.75, 0.75, 0.5, 1.0, 0.3, 1.0, 0.75, 0.8, 0.75, 0.75, 1.0, 0.55, 0.55, 0.7, 0.8, 0.75, 0.62, 0.8, 0.75, 0.52, 0.62, 0.8, 1.0, 1.0, 1.0, 1.0, 0.8, 0.75, 0.75, 0.6, 0.8, 0.6, 0.75, 0.95, 0.4, 0.55, 0.65, 0.6, 0.62, 0.3, 0.2, 1.0, 0.4, 0.75, 0.2, 0.5, 0.75, 0.8, 1.0, 0.6, 0.7, 0.75, 0.8, 0.75, 0.49000000000000005, 0.65, 0.9, 1.0, 0.8, 0.55, 0.8, 0.2, 0.0, 0.75, 0.35, 0.75, 0.95, 0.9, 0.75, 0.75, 0.7, 0.75, 1.0, 0.8, 0.55, 0.75, 1.0, 0.0, 0.65, 1.0, 0.6, 0.5, 0.52, 0.75, 1.0, 1.0, 0.1, 0.1, 0.45, 0.7, 1.0, 1.0, 1.0, 1.0, 0.8, 0.6, 0.95, 1.0, 0.75, 0.7, 0.65, 0.7, 0.75, 0.65, 0.4, 0.9, 1.0, 1.0, 1.0, 0.75, 0.8, 0.95, 0.3, 1.0, 0.75, 0.55, 0.7, 0.6, 0.5, 1.0, 0.2, 0.8, 0.7, 0.75, 0.62, 0.6, 0.65, 1.0, 0.8, 0.4, 0.15, 0.95, 0.75, 0.62, 0.7, 1.0, 0.9, 0.65, 1.0, 0.1, 0.1, 1.0, 0.2, 1.0, 0.75, 0.4, 0.8, 1.0, 0.75, 0.3, 0.8, 0.9, 0.65, 0.8, 0.75, 0.5, 0.45, 0.6, 0.8, 0.4, 0.75, 0.75, 1.0, 0.8, 0.7, 0.7, 0.6, 0.85, 1.0, 0.6, 1.0, 1.0, 0.9, 0.8, 0.3, 0.8, 1.0, 0.62, 0.65, 1.0, 0.55, 0.7, 0.55, 1.0, 0.75, 0.4, 0.9, 0.8, 1.0, 0.8, 0.8, 0.6, 0.8, 1.0, 0.1, 0.65, 0.8, 0.8, 0.7, 0.75, 1.0, 0.6, 0.2800000000000001, 1.0, 1.0, 1.0, 0.7, 0.85, 1.0, 0.9, 0.62, 0.7, 0.4, 1.0, 0.75, 0.5, 0.4, 0.8, 1.0, 1.0, 0.65, 0.65, 0.8, 1.0, 0.8, 0.75, 0.8, 0.75, 0.7, 0.8, 0.75, 0.6, 0.8, 0.7, 0.75, 0.75, 0.65, 0.75, 0.6, 0.75, 1.0, 0.65, 0.75, 0.85, 1.0, 1.0, 0.1, 0.9, 0.75, 0.3, 0.65, 0.36, 0.75, 1.0, 0.75, 0.95, 0.4, 1.0, 1.0, 0.55, 0.5, 0.75, 0.6, 0.3, 0.0, 0.65, 1.0, 0.75, 0.6, 0.95, 0.55, 0.6, 0.75, 1.0, 0.6, 0.62, 1.0, 1.0, 1.0, 0.55, 0.49000000000000005, 0.6, 1.0, 1.0, 0.52, 0.75, 1.0, 0.85, 1.0, 1.0, 0.6, 0.5700000000000001, 0.75, 1.0, 1.0, 0.2, 0.75, 0.9, 0.8, 0.8, 0.36, 0.95, 0.8, 0.65, 0.6, 0.8, 0.7, 0.5700000000000001, 0.65, 0.45, 1.0, 1.0, 0.8, 0.7, 1.0, 1.0, 0.6, 1.0, 0.75, 0.62, 1.0, 0.9, 1.0, 0.62, 0.7, 0.1, 0.8, 0.6, 0.3, 0.95, 0.45, 0.9, 1.0, 0.75, 0.2, 1.0, 0.6, 0.75, 0.2, 1.0, 0.1, 0.8, 0.8, 0.5, 0.2, 0.65, 0.0, 0.85, 1.0, 1.0, 1.0, 1.0, 0.6, 1.0, 0.7, 1.0, 0.75, 0.7, 0.62, 0.7, 1.0, 0.8, 0.0, 0.75, 1.0, 0.7, 0.65, 0.4, 1.0, 0.65, 0.75, 0.62, 0.15, 0.6, 0.3, 0.75, 0.45, 0.75, 0.7, 0.8, 0.2, 0.4, 0.75, 1.0, 0.65, 1.0, 1.0, 0.6, 0.3, 1.0, 0.6, 1.0, 0.75, 0.75, 1.0, 1.0, 1.0, 1.0, 0.55, 0.7, 0.55, 1.0, 1.0, 1.0, 0.7, 0.55, 0.75, 0.7, 1.0, 0.7, 0.8, 1.0, 0.85, 0.4, 0.6, 0.36, 0.95, 0.5, 0.65, 0.75, 0.62, 0.8, 0.9, 1.0, 0.6, 0.62, 0.5, 1.0, 0.62, 1.0, 0.7, 0.8, 1.0, 1.0, 0.4, 1.0, 0.4, 0.6, 0.0, 1.0, 0.8, 0.65, 0.8, 1.0, 1.0, 0.4, 0.7, 1.0, 0.8, 0.8, 1.0, 1.0, 1.0, 1.0, 1.0, 0.8, 0.7, 1.0, 0.3, 0.75, 1.0, 0.5, 0.0, 0.4, 0.9, 0.4, 0.8, 0.8, 0.4, 1.0, 0.5, 0.55, 0.6, 0.55, 0.55, 0.5, 0.8, 1.0, 0.8, 1.0, 0.6, 0.62, 0.8, 0.62, 0.6, 0.8, 0.9, 0.8, 0.75, 0.8, 0.75, 0.75, 0.75, 0.75, 0.9, 0.9, 0.9, 0.95, 0.75, 0.6, 0.95, 0.6, 0.85, 0.8, 0.8, 0.62, 1.0, 1.0, 0.75, 1.0, 0.0, 1.0, 0.8, 0.75, 1.0, 0.75, 0.6, 0.5, 0.4, 1.0, 0.4, 1.0, 0.0, 0.4, 0.65, 0.75, 0.95, 0.8, 0.8, 0.6, 1.0, 0.8, 0.75, 0.9, 0.65, 0.2, 0.65, 1.0, 0.5, 0.8, 0.62, 1.0, 0.8, 0.67, 0.8, 0.49000000000000005, 0.85, 0.4, 0.7, 0.75, 0.75, 0.65, 0.5, 0.2, 0.8, 1.0, 0.75, 0.75, 0.75, 0.1, 0.8, 0.8, 1.0, 0.1, 0.6, 0.8, 0.7, 0.1, 0.62, 1.0, 1.0, 0.5, 0.75, 0.4, 1.0, 0.6, 1.0, 0.75, 0.75, 1.0, 0.62, 0.5700000000000001, 0.9, 0.8, 0.75, 0.75, 1.0, 1.0, 1.0, 1.0, 0.8, 0.75, 0.49000000000000005, 1.0, 1.0, 0.55, 0.55, 0.85, 0.4, 0.6, 0.75, 0.4, 1.0, 1.0, 0.9, 0.7, 0.62, 0.65, 0.6, 0.62, 0.65, 1.0, 0.6, 0.65, 1.0, 0.8, 0.15, 0.7, 1.0, 1.0, 1.0, 0.65, 1.0, 0.9, 1.0, 0.35, 1.0, 0.8, 0.65, 0.6, 0.85, 0.75, 0.6, 0.4, 0.4, 0.75, 1.0, 0.85, 0.7, 0.8, 0.65, 0.45, 0.8, 0.85, 0.3, 0.8, 0.8, 0.7, 0.6, 0.55, 0.8, 0.75, 0.75, 0.6, 0.55, 0.7, 1.0, 0.7, 0.8, 0.2, 0.7, 0.8, 1.0, 0.6, 1.0, 1.0, 0.8, 0.6, 0.2, 0.75, 0.75, 0.8, 0.6, 0.3, 0.8, 0.7, 0.6, 0.75, 0.85, 0.8, 0.75, 0.3, 0.75, 0.65, 0.6, 0.4, 0.75, 1.0, 1.0, 0.1, 0.2, 0.55, 0.75, 1.0, 0.4, 0.75, 0.2, 0.75, 1.0, 0.75, 1.0, 0.5, 0.65, 0.6, 0.95, 0.8, 1.0, 0.5700000000000001, 0.5700000000000001, 0.4, 0.5, 0.7, 0.2, 0.4, 1.0, 1.0, 1.0, 0.8, 1.0, 0.4, 0.7, 0.9, 1.0, 0.8, 0.7, 0.8, 1.0, 0.4, 0.8, 0.8, 1.0, 1.0, 0.75, 0.7, 1.0, 0.5, 0.62, 0.8, 0.3, 0.8, 0.7, 0.75, 1.0, 0.95, 0.7, 0.75, 0.65, 0.7, 0.9, 0.75, 0.7, 0.52, 0.75, 0.62, 0.7, 0.65, 1.0, 0.5, 0.75, 0.3, 1.0, 0.8, 0.5, 0.7, 0.8, 0.75, 0.75, 0.75, 1.0, 0.4, 1.0, 0.75, 0.6, 0.6, 0.62, 0.3, 0.75, 1.0, 1.0, 0.7, 0.62, 0.1, 0.8, 0.8, 0.75, 0.75, 0.3, 0.8, 0.65, 0.7, 1.0, 1.0, 0.8, 1.0, 1.0, 0.6, 1.0, 0.7, 0.8, 0.9, 0.55, 1.0, 0.65, 0.62, 0.65, 0.3, 1.0, 0.4, 1.0, 0.2, 0.8, 0.8, 0.55, 0.62, 0.8, 0.95, 0.75, 0.62, 0.75, 0.65, 0.9, 1.0, 1.0, 0.7, 0.8, 1.0, 0.75, 0.62, 0.65, 0.75, 0.52, 0.6, 1.0, 1.0, 1.0, 0.6, 0.6, 1.0, 1.0, 0.75, 0.62, 0.95, 0.8, 0.6, 0.62, 0.8, 0.75, 1.0, 1.0, 1.0, 1.0, 0.55, 0.1, 0.75, 0.75, 0.75, 0.95, 0.5, 0.0, 0.0, 0.75, 0.1, 0.75, 0.6, 0.62, 0.8, 0.8, 0.7, 0.95, 1.0, 0.1, 0.65, 1.0, 0.9, 0.7, 0.75, 0.8, 0.6, 0.1, 0.8, 0.8, 0.62, 0.75, 0.65, 0.62, 1.0, 0.55, 0.55, 0.3, 0.7, 0.9, 0.9, 1.0, 0.39, 0.5, 0.75, 0.8, 0.5, 0.8, 0.8, 0.8, 0.75, 1.0, 0.9, 0.8, 1.0, 0.8, 0.8, 1.0, 1.0, 0.75, 0.5, 0.7, 0.8, 1.0, 0.85, 0.85, 1.0, 0.6, 0.65, 1.0, 0.7, 0.2, 1.0, 1.0, 1.0, 0.75, 0.3, 0.5, 0.55, 1.0, 0.6, 1.0, 0.6, 0.8, 0.75, 0.75, 0.62, 0.7, 0.8, 1.0, 0.75, 1.0, 1.0, 0.75, 0.8, 0.7, 0.62, 1.0, 1.0, 0.75, 0.7, 0.62, 0.8, 0.55, 0.5, 0.2, 0.75, 0.65, 0.5, 0.3, 0.8, 0.7, 0.75, 0.0, 1.0, 1.0, 1.0, 0.0, 1.0, 1.0, 0.8, 0.9, 0.1, 0.85, 1.0, 0.4, 0.5, 1.0, 0.75, 0.62, 0.75, 1.0, 0.3, 0.95, 0.8, 0.6, 0.75, 0.8, 0.75, 1.0, 0.7, 1.0, 1.0, 0.75, 0.9, 0.62, 1.0, 1.0, 0.8, 0.8, 0.65, 0.3, 0.9, 0.8, 1.0, 0.8, 0.7, 0.6, 0.62, 0.5, 1.0, 0.95, 0.75, 0.85, 0.65, 0.62, 0.8, 0.5, 0.5, 0.4, 0.8, 0.75, 0.85, 1.0, 1.0, 1.0, 0.8, 0.7, 1.0, 0.62, 0.5, 1.0, 0.6, 0.95, 0.62, 0.62, 0.62, 0.7, 0.62, 0.65, 0.62, 1.0, 0.75, 0.62, 0.6, 0.75, 0.7, 0.95, 1.0, 0.3, 0.85, 0.7, 0.65, 0.7, 1.0, 0.4, 0.8, 1.0, 0.6, 0.75, 0.2, 0.95, 1.0, 0.7, 0.7, 0.65, 0.8, 0.4, 0.75, 0.5700000000000001, 0.75, 0.75, 0.75, 0.62, 1.0, 0.8, 0.8, 0.65, 1.0, 1.0, 1.0, 0.4, 0.4, 1.0, 0.4, 0.6, 0.8, 0.75, 0.0, 0.8, 1.0, 0.25, 0.15, 0.75, 0.75, 1.0, 0.8, 0.75, 1.0, 1.0, 0.6, 0.65, 0.45, 0.49000000000000005, 0.75, 0.22000000000000003, 0.2, 0.47000000000000003, 0.8, 0.95, 0.27, 0.75, 0.75, 0.49000000000000005, 0.75, 0.75, 0.15, 0.75, 0.55, 0.75, 0.7, 0.75, 0.55, 0.6, 0.33999999999999997, 0.55, 0.45, 0.4, 0.7, 0.6, 0.62, 0.2, 0.75, 0.6, 0.55, 0.6, 0.65, 0.55, 0.4, 0.7, 0.55, 0.75, 0.8, 0.6, 0.7, 0.1, 0.75, 0.75, 0.75, 0.75, 0.6, 0.7, 0.75, 0.75, 0.75, 0.9, 0.7, 0.75, 0.45, 0.6, 1.0, 0.15, 0.62, 1.0, 0.6, 0.75, 0.27999999999999997, 0.6, 0.55, 0.75, 0.55, 0.75, 0.75, 0.45, 0.85, 0.6, 0.75, 0.45, 0.45, 0.36, 0.0, 0.75, 0.75, 0.8, 0.64, 0.15, 0.8, 0.75, 0.8, 0.9, 0.45, 0.75, 0.75, 0.47000000000000003, 0.26000000000000006, 0.5700000000000001, 0.7, 0.75, 0.6, 0.6, 0.75, 0.75, 0.6, 0.25, 0.7, 0.7, 0.7, 0.3, 0.75, 0.65, 0.75, 0.5, 0.6, 0.75, 0.55, 0.75, 0.6, 0.75, 0.15, 0.55, 0.25, 0.7, 1.0, 0.55, 0.1, 0.75, 0.6, 0.75, 0.95, 0.75, 0.75, 0.55, 0.6, 0.55, 0.55, 0.5, 0.6, 0.55, 0.1, 0.65, 0.75, 0.6, 0.4, 0.45, 0.7, 0.75, 0.75, 0.8, 0.8, 0.6, 0.65, 0.45, 0.7, 0.7, 0.65, 0.55, 0.75, 0.45, 0.65, 0.18, 0.44000000000000006, 0.18, 0.8, 0.75, 0.75, 0.75, 0.75, 0.75, 0.55, 0.75, 0.55, 1.0, 0.75, 0.75, 0.6, 0.19, 0.25999999999999995, 0.75, 0.75, 0.6, 0.75, 0.6, 0.4, 0.21000000000000002, 0.85, 0.3, 0.75, 0.45, 0.8, 0.4, 0.62, 0.64, 0.0, 0.75, 0.75, 0.26, 0.45, 0.49000000000000005, 0.6, 0.85, 0.8, 0.5700000000000001, 0.45, 0.75, 0.75, 0.6, 0.65, 0.65, 0.49000000000000005, 0.6, 0.5700000000000001, 0.65, 0.7, 0.6, 0.8, 1.0, 0.75, 0.75, 0.47000000000000003, 0.47000000000000003, 0.75, 0.75, 0.0, 0.3, 0.49000000000000005, 0.75, 0.75, 0.65, 0.52, 0.6, 0.3, 0.75, 0.45, 0.55, 0.75, 0.7, 0.0, 0.75, 0.08, 0.36, 0.62, 0.6, 0.0, 0.5, 1.0, 0.42000000000000004, 1.0, 0.55, 0.9, 1.0, 0.75, 0.8, 0.8, 0.35, 0.85, 0.29, 0.28, 0.45, 0.45, 0.75, 0.75, 0.75, 0.2, 0.75, 0.33999999999999997, 0.8, 0.25, 0.5, 0.75, 0.45, 0.49000000000000005, 0.45, 0.7, 0.75, 0.75, 0.25, 0.6, 0.7, 0.75, 0.36, 0.35, 0.75, 0.6, 0.15, 0.55, 0.5700000000000001, 0.7, 0.1, 0.26000000000000006, 0.8, 0.6, 0.75, 0.75, 0.62, 0.45, 0.75, 0.75, 0.6, 0.75, 0.75, 0.75, 0.8, 0.55, 0.75, 0.47000000000000003, 0.36, 0.1, 0.18, 0.3, 0.75, 0.7, 0.49000000000000005, 0.62, 0.75, 0.62, 0.45, 0.75, 0.6, 0.75, 0.75, 0.75, 0.75, 0.4, 0.33999999999999997, 0.6, 0.35, 0.32, 0.47000000000000003, 0.47000000000000003, 0.62, 0.49000000000000005, 0.75, 0.7, 0.75, 0.22999999999999998, 0.75, 0.75, 0.75, 0.44000000000000006, 0.7, 0.75, 0.62, 0.1, 0.1, 0.2800000000000001, 0.27999999999999997, 0.75, 0.75, 0.6, 0.75, 0.75, 0.85, 0.75, 0.75, 0.75, 0.95, 0.62, 0.75, 0.6, 0.75, 0.8, 1.0, 1.0, 0.75, 0.75, 0.6, 0.8, 0.75, 0.7, 1.0, 0.75, 0.65, 0.65, 0.62, 0.75, 0.6, 1.0, 0.95, 0.7, 0.62, 0.75, 0.6, 0.47000000000000003, 0.44000000000000006, 0.65, 0.22999999999999998, 0.75, 0.7, 0.55, 0.45, 0.75, 0.75, 0.75, 0.75, 0.8, 1.0, 0.75, 0.75, 0.75, 0.49000000000000005, 0.67, 0.75, 1.0, 0.75, 0.75, 0.75, 0.75, 0.75, 1.0, 1.0, 0.75, 0.75, 0.85, 1.0, 0.75, 0.75, 0.7, 0.49000000000000005, 0.75, 0.62, 0.95, 0.75, 0.75, 0.75, 0.75, 0.75, 0.95, 0.47000000000000003, 0.6, 0.9, 0.6, 0.75, 0.7, 0.7, 1.0, 1.0, 0.1, 0.75, 0.44000000000000006, 0.49000000000000005, 0.8, 0.75, 0.75, 0.75, 0.75, 0.75, 0.65, 0.75, 0.45, 0.75, 0.75, 0.7, 0.75, 0.9, 0.1, 0.75, 0.6, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 1.0, 0.8, 0.75, 0.75, 0.75, 0.75, 0.9, 0.75, 0.75, 0.85, 0.42000000000000004, 0.37, 0.44000000000000006, 0.55, 0.65, 0.1, 1.0, 0.5, 0.7, 0.7, 1.0, 0.75, 0.75, 0.4, 0.45, 0.7, 0.6, 0.75, 0.75, 0.75, 0.75, 0.75, 0.75, 0.25, 0.85, 0.75, 0.33999999999999997, 0.75, 0.8, 0.6, 0.75, 0.75, 0.2800000000000001, 0.75, 0.75, 0.75, 0.18, 0.75, 0.2800000000000001, 0.18, 0.18, 0.75, 0.75, 0.9, 1.0, 0.8, 0.75, 0.75, 0.1, 0.75, 0.8, 0.75, 0.75, 0.8, 0.75, 0.75, 1.0, 0.9, 1.0, 0.8, 1.0, 0.6, 1.0, 0.75, 0.62, 0.6, 0.75, 1.0, 0.75, 0.3, 0.75, 0.47000000000000003, 0.95, 0.75, 0.75, 0.8, 0.75, 0.62, 0.75, 0.75, 0.6, 0.75, 0.7, 0.85, 1.0, 0.18, 0.62, 0.75, 0.75, 0.45, 0.8, 0.49000000000000005, 0.47000000000000003, 0.9, 0.49000000000000005, 0.1, 0.75, 0.47000000000000003, 0.75, 0.6, 0.75, 0.75, 0.75, 0.6, 0.9, 0.3, 0.75, 0.75, 0.9, 0.75, 0.9, 0.75, 0.75, 0.75, 0.75, 0.75, 0.55, 0.6, 0.75, 0.49000000000000005, 0.95, 1.0, 0.75, 0.75, 0.5700000000000001, 0.75, 0.75, 0.47000000000000003, 0.75, 0.7, 0.75, 0.62, 0.1, 0.1, 0.1, 0.65, 0.5700000000000001, 0.75, 1.0, 0.75, 0.29, 0.35, 0.75, 0.75, 0.65, 0.95, 0.65, 0.7, 0.75, 0.75, 0.18, 0.6, 0.49000000000000005, 0.5700000000000001, 0.7, 0.18, 0.5700000000000001, 0.49000000000000005, 0.75, 0.7, 0.4, 0.8, 0.75, 0.8, 0.7, 0.6, 0.3, 0.6, 0.75, 0.75, 0.65, 0.75, 1.0, 0.75, 0.5, 0.65, 0.75, 0.75, 0.75, 0.6, 0.75, 0.75, 0.8, 0.9, 0.6, 0.75, 0.75, 0.85, 0.62, 0.65, 0.8, 0.75, 1.0, 0.7, 1.0, 1.0, 0.55, 0.72, 0.36, 0.75, 0.75, 1.0, 0.7, 0.75, 0.7, 0.85, 0.6, 0.75, 0.75, 0.55, 0.4, 0.75, 0.65, 0.7, 0.75, 0.75, 0.6, 0.75, 0.45, 0.7, 0.9, 0.6, 0.8, 0.75, 0.75, 0.75, 0.55, 0.8, 0.75, 0.75, 0.7, 0.8, 0.8, 0.8, 1.0, 0.2, 0.6, 1.0, 0.3, 0.7, 0.45, 0.8, 0.75, 0.75, 0.49000000000000005, 0.62, 0.47000000000000003, 0.85, 0.7, 0.75, 0.8, 0.75, 0.65, 0.6, 0.7, 0.75, 0.55, 0.75, 0.2, 0.8, 0.4600000000000001, 0.75, 0.62, 0.49000000000000005, 0.75, 0.75, 0.7, 0.33999999999999997, 1.0, 0.95, 0.5, 0.5, 0.45, 0.75, 0.75, 0.75, 0.75, 0.8, 0.6, 0.62, 0.75, 0.75, 0.75, 0.75, 0.75, 1.0, 0.75, 0.1, 0.55, 0.65, 0.65, 0.75, 0.6, 0.8, 1.0, 0.75, 0.75, 1.0, 0.55, 0.75, 0.75, 0.75, 0.75, 0.5700000000000001, 0.7, 0.75, 0.7, 0.1, 0.6, 0.75, 1.0, 0.5, 0.8, 0.75, 0.65, 0.47000000000000003, 0.8, 0.6, 0.7, 0.75, 0.8, 0.65, 0.75, 0.75, 0.75, 0.75, 0.75, 0.9, 0.75, 0.85, 0.75, 0.75, 0.75, 0.75, 0.8, 0.62, 0.95, 0.6, 0.7, 0.49000000000000005, 0.65, 0.75, 0.75, 0.75, 0.5, 0.7, 0.1, 0.7, 0.65, 1.0, 0.8, 0.6, 1.0, 0.6, 0.7, 0.47000000000000003, 0.55, 0.75, 0.5, 0.55, 0.8, 0.6, 0.75, 0.7, 0.7, 0.75, 0.65, 0.75, 0.75, 0.64, 0.75, 0.75, 0.7, 0.65, 0.65, 0.33999999999999997, 0.55, 0.8, 1.0, 0.6, 0.75, 0.75, 0.65, 0.47000000000000003, 0.49000000000000005, 0.75, 0.8, 0.1, 0.49000000000000005, 0.9, 0.4, 0.75, 0.75, 0.75, 0.7, 0.75, 0.75, 0.55, 0.36, 0.9, 0.9, 1.0, 0.75, 0.75, 0.75, 0.55, 0.75, 0.75, 0.1, 0.75, 0.55, 0.6, 0.75, 0.6, 0.75, 0.75, 0.65, 0.75, 0.75, 0.5700000000000001, 0.22999999999999998, 0.4600000000000001, 0.1, 0.7, 0.75, 0.5700000000000001, 0.75, 0.75, 0.75, 0.62, 0.9, 0.45, 0.62, 0.85, 0.1, 0.62, 0.49000000000000005, 0.75, 1.0, 0.75, 0.75, 0.4, 0.6, 0.6, 0.5700000000000001, 0.75, 0.7, 0.45, 0.62, 0.62, 0.45, 0.75, 0.6, 0.7, 0.6, 0.75, 0.4, 0.55, 0.62, 0.75, 0.75, 0.6, 0.6, 0.30999999999999994, 0.62, 0.75, 0.62, 0.6, 0.67, 0.65, 0.75, 0.9, 0.75, 0.75, 0.62, 1.0, 0.75, 0.75, 0.75, 0.49000000000000005, 0.62, 0.49000000000000005, 0.7, 0.75, 0.85, 0.75, 0.95, 0.65, 0.62, 0.52, 0.55, 0.62, 0.75, 0.75, 0.7, 0.75, 0.7, 0.1, 0.75, 0.75, 0.7, 0.1, 0.1, 0.62, 0.22999999999999998, 0.1, 0.5700000000000001, 0.75, 1.0, 0.85, 0.75, 0.7, 0.65, 0.8, 0.75, 1.0, 0.3, 0.9, 0.8, 0.5, 1.0, 0.65, 0.7, 0.2, 0.7, 1.0, 0.55, 0.7, 0.8, 0.62, 0.8, 0.8, 0.65, 0.6, 0.9, 0.8, 0.85, 0.9, 0.25, 0.95, 1.0, 0.9, 0.8, 1.0, 0.95, 0.5, 0.9, 1.0, 0.75, 0.75, 0.0, 0.62, 0.6, 0.75, 0.8, 0.65, 0.8, 0.9, 0.9, 0.3, 0.75, 0.1, 0.7, 1.0, 0.95, 1.0, 0.95, 0.75, 0.95, 0.75, 0.75, 0.75, 0.6, 0.65, 0.75, 0.7, 0.62, 0.6, 0.8, 0.8, 1.0, 0.4, 0.62, 1.0, 0.6, 1.0, 1.0, 0.85, 0.0, 1.0, 0.8, 0.5, 0.65, 0.55, 0.65, 1.0, 0.95, 0.5, 0.8, 0.65, 0.8, 0.55, 0.2, 0.55, 0.5, 1.0, 0.8, 0.6, 1.0, 1.0, 0.49000000000000005, 1.0, 0.85, 0.8, 0.65, 0.75, 0.5, 1.0, 0.52, 0.75, 0.6, 0.75, 0.7, 0.65, 0.0, 0.4, 0.2, 1.0, 0.8, 0.75, 1.0, 0.7, 0.8, 1.0, 1.0, 0.1, 0.6, 0.85, 0.8, 0.4, 1.0, 0.7, 0.6, 1.0, 0.8, 0.65, 0.65, 1.0, 0.75, 0.6, 1.0, 1.0, 0.65, 0.65, 0.4, 0.45, 0.8, 0.6, 0.85, 0.6, 0.95, 0.9, 0.7, 0.4, 1.0, 1.0, 0.8, 0.7, 0.75, 1.0, 0.85, 0.75, 1.0, 0.8, 1.0, 0.8, 1.0, 0.8, 0.8, 0.5, 0.85, 0.9, 0.9, 0.65, 1.0, 0.75, 1.0, 1.0, 0.49000000000000005, 0.6, 1.0, 0.75, 0.6, 0.4, 0.8, 0.8, 0.75, 0.5700000000000001, 0.75, 1.0, 0.75, 0.75, 0.7, 0.8, 0.65, 0.75, 0.62, 0.75, 0.4, 0.75, 0.75, 0.75, 0.7, 0.75, 0.75, 0.75, 1.0, 0.6, 0.25, 0.65, 0.9, 0.65, 0.75, 0.6, 1.0, 1.0, 0.75, 1.0, 0.8, 0.5700000000000001, 0.62, 0.5, 1.0, 0.8, 1.0, 0.8, 0.8, 0.75, 0.95, 0.65, 0.5700000000000001, 0.65, 0.8, 0.7, 0.85, 0.85, 0.85, 0.5, 0.95, 0.85, 0.82, 0.27999999999999997, 0.75, 0.7, 0.5700000000000001, 0.5, 0.6, 1.0, 0.75, 1.0, 0.85, 0.5, 0.75, 0.6, 0.5700000000000001, 0.7, 0.6, 1.0, 1.0, 0.8, 0.4, 0.4, 0.75, 0.5, 0.95, 0.8, 1.0, 0.4, 0.75, 0.75, 1.0, 1.0, 0.5, 0.8, 0.65, 0.6, 0.6, 0.75, 0.62, 0.95, 0.5700000000000001, 0.3, 1.0, 0.55, 1.0, 0.5, 0.75, 0.65, 0.75, 0.9, 1.0, 0.7, 1.0, 0.8, 1.0, 1.0, 0.62, 0.8, 0.9, 0.75, 0.62, 0.6, 0.65, 0.6, 0.8, 0.8, 0.4, 0.44000000000000006, 0.62, 0.6, 1.0, 0.4, 0.8, 0.9, 0.4, 0.7, 1.0, 0.65, 0.6, 0.6, 1.0, 0.7, 0.44000000000000006, 0.75, 0.4, 0.85, 1.0, 0.7, 0.62, 0.8, 0.4, 0.75, 0.75, 0.75, 1.0, 0.7, 0.75, 0.8, 0.8, 0.8, 0.85, 0.8, 1.0, 0.5, 0.8, 1.0, 1.0, 1.0, 0.9, 0.8, 0.5, 0.5, 0.85, 0.75, 0.55, 0.8, 0.75, 0.3, 0.55, 0.2, 0.55, 0.6, 0.5, 0.4, 1.0, 0.6, 0.75, 0.1, 1.0, 0.5700000000000001, 0.8, 0.35, 1.0, 0.8, 0.8, 0.8, 0.85, 0.8, 0.5, 0.6, 0.7, 0.52, 0.75, 0.8, 0.1, 0.95, 0.2, 0.6, 1.0, 0.85, 0.75, 0.8, 0.8, 0.75, 0.75, 0.7, 0.7, 0.75, 0.7, 0.6, 0.3, 0.95, 1.0, 1.0, 0.75, 0.4, 0.7, 0.4, 0.8, 0.62, 0.8, 0.6, 1.0, 0.75, 1.0, 0.5700000000000001, 0.8, 0.5, 0.6, 1.0, 0.7, 0.75, 1.0, 0.75, 0.7, 1.0, 0.55, 0.8, 1.0, 0.62, 0.8, 0.5, 0.1, 0.8, 0.8, 1.0, 1.0, 0.8, 0.4, 0.2, 0.8]

In [ ]:
queries.describe()

           measure
count  2594.000000
mean      0.697513
std       0.220151
min       0.000000
25%       0.600000
50%       0.750000
75%       0.800000
max       1.000000

In [ ]:
undersampled_queries = queries.sample(n=300, random_state=42)  # Set random_state for reproducibility
undersampled_queries.head()

             PID                                              PLAIN
211   PLAIN-1264                                             gluten
2121   PLAIN-425  soy-based ( gardein ) vs. mycoprotein-based ( ...
1738  PLAIN-3088                   is vitamin d the new vitamin e ?
2292   PLAIN-635                                 ayurvedic medicine
1669  PLAIN-2994      meat-borne infection risk from shopping carts

In [ ]:
undersampled_queries.to_csv('/content/drive/MyDrive/NLP/QueriesUndersampling.csv', index=False)

In [ ]:
columns = ['PID', 'DocID', 'Relation']
relationUndersampled2 = pd.DataFrame(columns=columns)
# c=r['DocID']
# print(c)

for index, row in relationUndersampled.iterrows():
  print(index)
  if row['PID'] in undersampled_queries['PID'].tolist():
     relationUndersampled2.loc[len(relationUndersampled2)] = [row['PID'], row['DocID'], row['Relation']]

Streaming output truncated to the last 5000 lines.
16202
16203
16204
16205
16206
16207
16208
16209
16210
16211
16212
16213
16214
16215
16216
16217
16218
16219
16220
16221
16222
16223
16224
16225
16226
16227
16228
16229
16230
16231
16232
16233
16234
16235
16236
16237
16238
16239
16240
16241
16242
16243
16244
16245
16246
16247
16248
16249
16250
16251
16252
16253
16254
16255
16256
16257
16258
16259
16260
16261
16262
16263
16264
16265
16266
16267
16268
16269
16270
16271
16272
16273
16274
16275
16276
16277
16278
16279
16280
16281
16282
16283
16284
16285
16286
16287
16288
16289
16290
16291
16292
16293
16294
16295
16296
16297
16298
16299
16300
16301
16302
16303
16304
16305
16306
16307
16308
16309
16310
16311
16312
16313
16314
16315
16316
16317
16318
16319
16320
16321
16322
16323
16324
16325
16326
16327
16328
16329
16330
16331
16332
16333
16334
16335
16336
16337
16338
16339
16340
16341
16342
16343
16344
16345
16346
16347
16348
16349
16350
16351
16352
16353
16354
16355
16356
16357
16358
16359
16360
16361
16362
16363
16364
16365
16366
16367
16368
16369
16370
16371
16372
16373
16374
16375
16376
16377
16378
16379
16380
16381
16382
16383
16384
16385
16386
16387
16388
16389
16390
16391
16392
16393
16394
16395
16396
16397
16398
16399
16400
16401
16402
16403
16404
16405
16406
16407
16408
16409
16410
16411
16412
16413
16414
16415
16416
16417
16418
16419
16420
16421
16422
16423
16424
16425
16426
16427
16428
16429
16430
16431
16432
16433
16434
16435
16436
16437
16438
16439
16440
16441
16442
16443
16444
16445
16446
16447
16448
16449
16450
16451
16452
16453
16454
16455
16456
16457
16458
16459
16460
16461
16462
16463
16464
16465
16466
16467
16468
16469
16470
16471
16472
16473
16474
16475
16476
16477
16478
16479
16480
16481
16482
16483
16484
16485
16486
16487
16488
16489
16490
16491
16492
16493
16494
16495
16496
16497
16498
16499
16500
16501
16502
16503
16504
16505
16506
16507
16508
16509
16510
16511
16512
16513
16514
16515
16516
16517
16518
16519
16520
16521
16522
16523
16524
16525
16526
16527
16528
16529
16530
16531
16532
16533
16534
16535
16536
16537
16538
16539
16540
16541
16542
16543
16544
16545
16546
16547
16548
16549
16550
16551
16552
16553
16554
16555
16556
16557
16558
16559
16560
16561
16562
16563
16564
16565
16566
16567
16568
16569
16570
16571
16572
16573
16574
16575
16576
16577
16578
16579
16580
16581
16582
16583
16584
16585
16586
16587
16588
16589
16590
16591
16592
16593
16594
16595
16596
16597
16598
16599
16600
16601
16602
16603
16604
16605
16606
16607
16608
16609
16610
16611
16612
16613
16614
16615
16616
16617
16618
16619
16620
16621
16622
16623
16624
16625
16626
16627
16628
16629
16630
16631
16632
16633
16634
16635
16636
16637
16638
16639
16640
16641
16642
16643
16644
16645
16646
16647
16648
16649
16650
16651
16652
16653
16654
16655
16656
16657
16658
16659
16660
16661
16662
16663
16664
16665
16666
16667
16668
16669
16670
16671
16672
16673
16674
16675
16676
16677
16678
16679
16680
16681
16682
16683
16684
16685
16686
16687
16688
16689
16690
16691
16692
16693
16694
16695
16696
16697
16698
16699
16700
16701
16702
16703
16704
16705
16706
16707
16708
16709
16710
16711
16712
16713
16714
16715
16716
16717
16718
16719
16720
16721
16722
16723
16724
16725
16726
16727
16728
16729
16730
16731
16732
16733
16734
16735
16736
16737
16738
16739
16740
16741
16742
16743
16744
16745
16746
16747
16748
16749
16750
16751
16752
16753
16754
16755
16756
16757
16758
16759
16760
16761
16762
16763
16764
16765
16766
16767
16768
16769
16770
16771
16772
16773
16774
16775
16776
16777
16778
16779
16780
16781
16782
16783
16784
16785
16786
16787
16788
16789
16790
16791
16792
16793
16794
16795
16796
16797
16798
16799
16800
16801
16802
16803
16804
16805
16806
16807
16808
16809
16810
16811
16812
16813
16814
16815
16816
16817
16818
16819
16820
16821
16822
16823
16824
16825
16826
16827
16828
16829
16830
16831
16832
16833
16834
16835
16836
16837
16838
16839
16840
16841
16842
16843
16844
16845
16846
16847
16848
16849
16850
16851
16852
16853
16854
16855
16856
16857
16858
16859
16860
16861
16862
16863
16864
16865
16866
16867
16868
16869
16870
16871
16872
16873
16874
16875
16876
16877
16878
16879
16880
16881
16882
16883
16884
16885
16886
16887
16888
16889
16890
16891
16892
16893
16894
16895
16896
16897
16898
16899
16900
16901
16902
16903
16904
16905
16906
16907
16908
16909
16910
16911
16912
16913
16914
16915
16916
16917
16918
16919
16920
16921
16922
16923
16924
16925
16926
16927
16928
16929
16930
16931
16932
16933
16934
16935
16936
16937
16938
16939
16940
16941
16942
16943
16944
16945
16946
16947
16948
16949
16950
16951
16952
16953
16954
16955
16956
16957
16958
16959
16960
16961
16962
16963
16964
16965
16966
16967
16968
16969
16970
16971
16972
16973
16974
16975
16976
16977
16978
16979
16980
16981
16982
16983
16984
16985
16986
16987
16988
16989
16990
16991
16992
16993
16994
16995
16996
16997
16998
16999
17000
17001
17002
17003
17004
17005
17006
17007
17008
17009
17010
17011
17012
17013
17014
17015
17016
17017
17018
17019
17020
17021
17022
17023
17024
17025
17026
17027
17028
17029
17030
17031
17032
17033
17034
17035
17036
17037
17038
17039
17040
17041
17042
17043
17044
17045
17046
17047
17048
17049
17050
17051
17052
17053
17054
17055
17056
17057
17058
17059
17060
17061
17062
17063
17064
17065
17066
17067
17068
17069
17070
17071
17072
17073
17074
17075
17076
17077
17078
17079
17080
17081
17082
17083
17084
17085
17086
17087
17088
17089
17090
17091
17092
17093
17094
17095
17096
17097
17098
17099
17100
17101
17102
17103
17104
17105
17106
17107
17108
17109
17110
17111
17112
17113
17114
17115
17116
17117
17118
17119
17120
17121
17122
17123
17124
17125
17126
17127
17128
17129
17130
17131
17132
17133
17134
17135
17136
17137
17138
17139
17140
17141
17142
17143
17144
17145
17146
17147
17148
17149
17150
17151
17152
17153
17154
17155
17156
17157
17158
17159
17160
17161
17162
17163
17164
17165
17166
17167
17168
17169
17170
17171
17172
17173
17174
17175
17176
17177
17178
17179
17180
17181
17182
17183
17184
17185
17186
17187
17188
17189
17190
17191
17192
17193
17194
17195
17196
17197
17198
17199
17200
17201
17202
17203
17204
17205
17206
17207
17208
17209
17210
17211
17212
17213
17214
17215
17216
17217
17218
17219
17220
17221
17222
17223
17224
17225
17226
17227
17228
17229
17230
17231
17232
17233
17234
17235
17236
17237
17238
17239
17240
17241
17242
17243
17244
17245
17246
17247
17248
17249
17250
17251
17252
17253
17254
17255
17256
17257
17258
17259
17260
17261
17262
17263
17264
17265
17266
17267
17268
17269
17270
17271
17272
17273
17274
17275
17276
17277
17278
17279
17280
17281
17282
17283
17284
17285
17286
17287
17288
17289
17290
17291
17292
17293
17294
17295
17296
17297
17298
17299
17300
17301
17302
17303
17304
17305
17306
17307
17308
17309
17310
17311
17312
17313
17314
17315
17316
17317
17318
17319
17320
17321
17322
17323
17324
17325
17326
17327
17328
17329
17330
17331
17332
17333
17334
17335
17336
17337
17338
17339
17340
17341
17342
17343
17344
17345
17346
17347
17348
17349
17350
17351
17352
17353
17354
17355
17356
17357
17358
17359
17360
17361
17362
17363
17364
17365
17366
17367
17368
17369
17370
17371
17372
17373
17374
17375
17376
17377
17378
17379
17380
17381
17382
17383
17384
17385
17386
17387
17388
17389
17390
17391
17392
17393
17394
17395
17396
17397
17398
17399
17400
17401
17402
17403
17404
17405
17406
17407
17408
17409
17410
17411
17412
17413
17414
17415
17416
17417
17418
17419
17420
17421
17422
17423
17424
17425
17426
17427
17428
17429
17430
17431
17432
17433
17434
17435
17436
17437
17438
17439
17440
17441
17442
17443
17444
17445
17446
17447
17448
17449
17450
17451
17452
17453
17454
17455
17456
17457
17458
17459
17460
17461
17462
17463
17464
17465
17466
17467
17468
17469
17470
17471
17472
17473
17474
17475
17476
17477
17478
17479
17480
17481
17482
17483
17484
17485
17486
17487
17488
17489
17490
17491
17492
17493
17494
17495
17496
17497
17498
17499
17500
17501
17502
17503
17504
17505
17506
17507
17508
17509
17510
17511
17512
17513
17514
17515
17516
17517
17518
17519
17520
17521
17522
17523
17524
17525
17526
17527
17528
17529
17530
17531
17532
17533
17534
17535
17536
17537
17538
17539
17540
17541
17542
17543
17544
17545
17546
17547
17548
17549
17550
17551
17552
17553
17554
17555
17556
17557
17558
17559
17560
17561
17562
17563
17564
17565
17566
17567
17568
17569
17570
17571
17572
17573
17574
17575
17576
17577
17578
17579
17580
17581
17582
17583
17584
17585
17586
17587
17588
17589
17590
17591
17592
17593
17594
17595
17596
17597
17598
17599
17600
17601
17602
17603
17604
17605
17606
17607
17608
17609
17610
17611
17612
17613
17614
17615
17616
17617
17618
17619
17620
17621
17622
17623
17624
17625
17626
17627
17628
17629
17630
17631
17632
17633
17634
17635
17636
17637
17638
17639
17640
17641
17642
17643
17644
17645
17646
17647
17648
17649
17650
17651
17652
17653
17654
17655
17656
17657
17658
17659
17660
17661
17662
17663
17664
17665
17666
17667
17668
17669
17670
17671
17672
17673
17674
17675
17676
17677
17678
17679
17680
17681
17682
17683
17684
17685
17686
17687
17688
17689
17690
17691
17692
17693
17694
17695
17696
17697
17698
17699
17700
17701
17702
17703
17704
17705
17706
17707
17708
17709
17710
17711
17712
17713
17714
17715
17716
17717
17718
17719
17720
17721
17722
17723
17724
17725
17726
17727
17728
17729
17730
17731
17732
17733
17734
17735
17736
17737
17738
17739
17740
17741
17742
17743
17744
17745
17746
17747
17748
17749
17750
17751
17752
17753
17754
17755
17756
17757
17758
17759
17760
17761
17762
17763
17764
17765
17766
17767
17768
17769
17770
17771
17772
17773
17774
17775
17776
17777
17778
17779
17780
17781
17782
17783
17784
17785
17786
17787
17788
17789
17790
17791
17792
17793
17794
17795
17796
17797
17798
17799
17800
17801
17802
17803
17804
17805
17806
17807
17808
17809
17810
17811
17812
17813
17814
17815
17816
17817
17818
17819
17820
17821
17822
17823
17824
17825
17826
17827
17828
17829
17830
17831
17832
17833
17834
17835
17836
17837
17838
17839
17840
17841
17842
17843
17844
17845
17846
17847
17848
17849
17850
17851
17852
17853
17854
17855
17856
17857
17858
17859
17860
17861
17862
17863
17864
17865
17866
17867
17868
17869
17870
17871
17872
17873
17874
17875
17876
17877
17878
17879
17880
17881
17882
17883
17884
17885
17886
17887
17888
17889
17890
17891
17892
17893
17894
17895
17896
17897
17898
17899
17900
17901
17902
17903
17904
17905
17906
17907
17908
17909
17910
17911
17912
17913
17914
17915
17916
17917
17918
17919
17920
17921
17922
17923
17924
17925
17926
17927
17928
17929
17930
17931
17932
17933
17934
17935
17936
17937
17938
17939
17940
17941
17942
17943
17944
17945
17946
17947
17948
17949
17950
17951
17952
17953
17954
17955
17956
17957
17958
17959
17960
17961
17962
17963
17964
17965
17966
17967
17968
17969
17970
17971
17972
17973
17974
17975
17976
17977
17978
17979
17980
17981
17982
17983
17984
17985
17986
17987
17988
17989
17990
17991
17992
17993
17994
17995
17996
17997
17998
17999
18000
18001
18002
18003
18004
18005
18006
18007
18008
18009
18010
18011
18012
18013
18014
18015
18016
18017
18018
18019
18020
18021
18022
18023
18024
18025
18026
18027
18028
18029
18030
18031
18032
18033
18034
18035
18036
18037
18038
18039
18040
18041
18042
18043
18044
18045
18046
18047
18048
18049
18050
18051
18052
18053
18054
18055
18056
18057
18058
18059
18060
18061
18062
18063
18064
18065
18066
18067
18068
18069
18070
18071
18072
18073
18074
18075
18076
18077
18078
18079
18080
18081
18082
18083
18084
18085
18086
18087
18088
18089
18090
18091
18092
18093
18094
18095
18096
18097
18098
18099
18100
18101
18102
18103
18104
18105
18106
18107
18108
18109
18110
18111
18112
18113
18114
18115
18116
18117
18118
18119
18120
18121
18122
18123
18124
18125
18126
18127
18128
18129
18130
18131
18132
18133
18134
18135
18136
18137
18138
18139
18140
18141
18142
18143
18144
18145
18146
18147
18148
18149
18150
18151
18152
18153
18154
18155
18156
18157
18158
18159
18160
18161
18162
18163
18164
18165
18166
18167
18168
18169
18170
18171
18172
18173
18174
18175
18176
18177
18178
18179
18180
18181
18182
18183
18184
18185
18186
18187
18188
18189
18190
18191
18192
18193
18194
18195
18196
18197
18198
18199
18200
18201
18202
18203
18204
18205
18206
18207
18208
18209
18210
18211
18212
18213
18214
18215
18216
18217
18218
18219
18220
18221
18222
18223
18224
18225
18226
18227
18228
18229
18230
18231
18232
18233
18234
18235
18236
18237
18238
18239
18240
18241
18242
18243
18244
18245
18246
18247
18248
18249
18250
18251
18252
18253
18254
18255
18256
18257
18258
18259
18260
18261
18262
18263
18264
18265
18266
18267
18268
18269
18270
18271
18272
18273
18274
18275
18276
18277
18278
18279
18280
18281
18282
18283
18284
18285
18286
18287
18288
18289
18290
18291
18292
18293
18294
18295
18296
18297
18298
18299
18300
18301
18302
18303
18304
18305
18306
18307
18308
18309
18310
18311
18312
18313
18314
18315
18316
18317
18318
18319
18320
18321
18322
18323
18324
18325
18326
18327
18328
18329
18330
18331
18332
18333
18334
18335
18336
18337
18338
18339
18340
18341
18342
18343
18344
18345
18346
18347
18348
18349
18350
18351
18352
18353
18354
18355
18356
18357
18358
18359
18360
18361
18362
18363
18364
18365
18366
18367
18368
18369
18370
18371
18372
18373
18374
18375
18376
18377
18378
18379
18380
18381
18382
18383
18384
18385
18386
18387
18388
18389
18390
18391
18392
18393
18394
18395
18396
18397
18398
18399
18400
18401
18402
18403
18404
18405
18406
18407
18408
18409
18410
18411
18412
18413
18414
18415
18416
18417
18418
18419
18420
18421
18422
18423
18424
18425
18426
18427
18428
18429
18430
18431
18432
18433
18434
18435
18436
18437
18438
18439
18440
18441
18442
18443
18444
18445
18446
18447
18448
18449
18450
18451
18452
18453
18454
18455
18456
18457
18458
18459
18460
18461
18462
18463
18464
18465
18466
18467
18468
18469
18470
18471
18472
18473
18474
18475
18476
18477
18478
18479
18480
18481
18482
18483
18484
18485
18486
18487
18488
18489
18490
18491
18492
18493
18494
18495
18496
18497
18498
18499
18500
18501
18502
18503
18504
18505
18506
18507
18508
18509
18510
18511
18512
18513
18514
18515
18516
18517
18518
18519
18520
18521
18522
18523
18524
18525
18526
18527
18528
18529
18530
18531
18532
18533
18534
18535
18536
18537
18538
18539
18540
18541
18542
18543
18544
18545
18546
18547
18548
18549
18550
18551
18552
18553
18554
18555
18556
18557
18558
18559
18560
18561
18562
18563
18564
18565
18566
18567
18568
18569
18570
18571
18572
18573
18574
18575
18576
18577
18578
18579
18580
18581
18582
18583
18584
18585
18586
18587
18588
18589
18590
18591
18592
18593
18594
18595
18596
18597
18598
18599
18600
18601
18602
18603
18604
18605
18606
18607
18608
18609
18610
18611
18612
18613
18614
18615
18616
18617
18618
18619
18620
18621
18622
18623
18624
18625
18626
18627
18628
18629
18630
18631
18632
18633
18634
18635
18636
18637
18638
18639
18640
18641
18642
18643
18644
18645
18646
18647
18648
18649
18650
18651
18652
18653
18654
18655
18656
18657
18658
18659
18660
18661
18662
18663
18664
18665
18666
18667
18668
18669
18670
18671
18672
18673
18674
18675
18676
18677
18678
18679
18680
18681
18682
18683
18684
18685
18686
18687
18688
18689
18690
18691
18692
18693
18694
18695
18696
18697
18698
18699
18700
18701
18702
18703
18704
18705
18706
18707
18708
18709
18710
18711
18712
18713
18714
18715
18716
18717
18718
18719
18720
18721
18722
18723
18724
18725
18726
18727
18728
18729
18730
18731
18732
18733
18734
18735
18736
18737
18738
18739
18740
18741
18742
18743
18744
18745
18746
18747
18748
18749
18750
18751
18752
18753
18754
18755
18756
18757
18758
18759
18760
18761
18762
18763
18764
18765
18766
18767
18768
18769
18770
18771
18772
18773
18774
18775
18776
18777
18778
18779
18780
18781
18782
18783
18784
18785
18786
18787
18788
18789
18790
18791
18792
18793
18794
18795
18796
18797
18798
18799
18800
18801
18802
18803
18804
18805
18806
18807
18808
18809
18810
18811
18812
18813
18814
18815
18816
18817
18818
18819
18820
18821
18822
18823
18824
18825
18826
18827
18828
18829
18830
18831
18832
18833
18834
18835
18836
18837
18838
18839
18840
18841
18842
18843
18844
18845
18846
18847
18848
18849
18850
18851
18852
18853
18854
18855
18856
18857
18858
18859
18860
18861
18862
18863
18864
18865
18866
18867
18868
18869
18870
18871
18872
18873
18874
18875
18876
18877
18878
18879
18880
18881
18882
18883
18884
18885
18886
18887
18888
18889
18890
18891
18892
18893
18894
18895
18896
18897
18898
18899
18900
18901
18902
18903
18904
18905
18906
18907
18908
18909
18910
18911
18912
18913
18914
18915
18916
18917
18918
18919
18920
18921
18922
18923
18924
18925
18926
18927
18928
18929
18930
18931
18932
18933
18934
18935
18936
18937
18938
18939
18940
18941
18942
18943
18944
18945
18946
18947
18948
18949
18950
18951
18952
18953
18954
18955
18956
18957
18958
18959
18960
18961
18962
18963
18964
18965
18966
18967
18968
18969
18970
18971
18972
18973
18974
18975
18976
18977
18978
18979
18980
18981
18982
18983
18984
18985
18986
18987
18988
18989
18990
18991
18992
18993
18994
18995
18996
18997
18998
18999
19000
19001
19002
19003
19004
19005
19006
19007
19008
19009
19010
19011
19012
19013
19014
19015
19016
19017
19018
19019
19020
19021
19022
19023
19024
19025
19026
19027
19028
19029
19030
19031
19032
19033
19034
19035
19036
19037
19038
19039
19040
19041
19042
19043
19044
19045
19046
19047
19048
19049
19050
19051
19052
19053
19054
19055
19056
19057
19058
19059
19060
19061
19062
19063
19064
19065
19066
19067
19068
19069
19070
19071
19072
19073
19074
19075
19076
19077
19078
19079
19080
19081
19082
19083
19084
19085
19086
19087
19088
19089
19090
19091
19092
19093
19094
19095
19096
19097
19098
19099
19100
19101
19102
19103
19104
19105
19106
19107
19108
19109
19110
19111
19112
19113
19114
19115
19116
19117
19118
19119
19120
19121
19122
19123
19124
19125
19126
19127
19128
19129
19130
19131
19132
19133
19134
19135
19136
19137
19138
19139
19140
19141
19142
19143
19144
19145
19146
19147
19148
19149
19150
19151
19152
19153
19154
19155
19156
19157
19158
19159
19160
19161
19162
19163
19164
19165
19166
19167
19168
19169
19170
19171
19172
19173
19174
19175
19176
19177
19178
19179
19180
19181
19182
19183
19184
19185
19186
19187
19188
19189
19190
19191
19192
19193
19194
19195
19196
19197
19198
19199
19200
19201
19202
19203
19204
19205
19206
19207
19208
19209
19210
19211
19212
19213
19214
19215
19216
19217
19218
19219
19220
19221
19222
19223
19224
19225
19226
19227
19228
19229
19230
19231
19232
19233
19234
19235
19236
19237
19238
19239
19240
19241
19242
19243
19244
19245
19246
19247
19248
19249
19250
19251
19252
19253
19254
19255
19256
19257
19258
19259
19260
19261
19262
19263
19264
19265
19266
19267
19268
19269
19270
19271
19272
19273
19274
19275
19276
19277
19278
19279
19280
19281
19282
19283
19284
19285
19286
19287
19288
19289
19290
19291
19292
19293
19294
19295
19296
19297
19298
19299
19300
19301
19302
19303
19304
19305
19306
19307
19308
19309
19310
19311
19312
19313
19314
19315
19316
19317
19318
19319
19320
19321
19322
19323
19324
19325
19326
19327
19328
19329
19330
19331
19332
19333
19334
19335
19336
19337
19338
19339
19340
19341
19342
19343
19344
19345
19346
19347
19348
19349
19350
19351
19352
19353
19354
19355
19356
19357
19358
19359
19360
19361
19362
19363
19364
19365
19366
19367
19368
19369
19370
19371
19372
19373
19374
19375
19376
19377
19378
19379
19380
19381
19382
19383
19384
19385
19386
19387
19388
19389
19390
19391
19392
19393
19394
19395
19396
19397
19398
19399
19400
19401
19402
19403
19404
19405
19406
19407
19408
19409
19410
19411
19412
19413
19414
19415
19416
19417
19418
19419
19420
19421
19422
19423
19424
19425
19426
19427
19428
19429
19430
19431
19432
19433
19434
19435
19436
19437
19438
19439
19440
19441
19442
19443
19444
19445
19446
19447
19448
19449
19450
19451
19452
19453
19454
19455
19456
19457
19458
19459
19460
19461
19462
19463
19464
19465
19466
19467
19468
19469
19470
19471
19472
19473
19474
19475
19476
19477
19478
19479
19480
19481
19482
19483
19484
19485
19486
19487
19488
19489
19490
19491
19492
19493
19494
19495
19496
19497
19498
19499
19500
19501
19502
19503
19504
19505
19506
19507
19508
19509
19510
19511
19512
19513
19514
19515
19516
19517
19518
19519
19520
19521
19522
19523
19524
19525

In [ ]:
relationUndersampled2

             PID     DocID  Relation
0        PLAIN-4  MED-5323         1
1        PLAIN-4  MED-5324         1
2        PLAIN-4  MED-5327         1
3        PLAIN-4  MED-5329         1
4        PLAIN-4  MED-5332         1
...          ...       ...       ...
2115  PLAIN-3466  MED-3398         2
2116  PLAIN-3466  MED-3506         2
2117  PLAIN-3466  MED-3515         2
2118  PLAIN-3466  MED-3516         2
2119  PLAIN-3466  MED-4281         2

[2120 rows x 3 columns]

In [ ]:
relationUndersampled2.to_csv('/content/drive/MyDrive/NLP/RelationsUndersampled.csv', index=False)